#!/bin/bash
echo "Fixing JSX syntax errors..."
sed -i '' '254s/}/)}/' src/components/Navbar/Navbar.jsx && echo "✅ Navbar.jsx line 254"
sed -i '' '421s/}/)}/' src/pages/DosageGuide/DosageGuide.jsx && echo "✅ DosageGuide.jsx line 421"
sed -i '' '435s/}/)}/' src/pages/DosageGuide/DosageGuide.jsx && echo "✅ DosageGuide.jsx line 435"
sed -i '' '564s/}/)}/' src/pages/DosageGuide/DosageGuide.jsx && echo "✅ DosageGuide.jsx line 564"
sed -i '' '585s/}/)}/' src/pages/DosageGuide/DosageGuide.jsx && echo "✅ DosageGuide.jsx line 585"
sed -i '' '601s/}/)}/' src/pages/DosageGuide/DosageGuide.jsx && echo "✅ DosageGuide.jsx line 601"
sed -i '' '677s/}/)}/' src/pages/DosageGuide/DosageGuide.jsx && echo "✅ DosageGuide.jsx line 677"
sed -i '' '695s/}/)}/' src/pages/DosageGuide/DosageGuide.jsx && echo "✅ DosageGuide.jsx line 695"
sed -i '' '333s/}/)}/' src/pages/More/More.jsx && echo "✅ More.jsx line 333"
sed -i '' '431s/}/)}/' src/pages/More/More.jsx && echo "✅ More.jsx line 431"
sed -i '' '480s/}/)}/' src/pages/More/More.jsx && echo "✅ More.jsx line 480"
sed -i '' '184s/}/)}/' src/pages/Auth/ResetPassword.jsx && echo "✅ ResetPassword.jsx line 184"
sed -i '' '38s/}/)}/' src/pages/Notifications/NotificationCenter.jsx && echo "✅ NotificationCenter.jsx line 38"
echo ""
echo "✅ All fixes applied successfully!"
