version: '3.8'

services:
  wellnessos-app:
    build: .
    container_name: wellnessos-backend
    ports:
      - "5000:5000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://wellnessos-rds-db:3306/altheal_prod_db?createDatabaseIfNotExist=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=aws_production_secure_pass_123
    depends_on:
      wellnessos-rds-db:
        condition: service_healthy
    networks:
      - wellness-network

  wellnessos-rds-db:
    image: mysql:8.0
    container_name: wellnessos-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=aws_production_secure_pass_123
      - MYSQL_DATABASE=altheal_prod_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - wellness-network

networks:
  wellness-network:
    driver: bridge
