echo "Add these dependencies to pom.xml if not present:"
echo ""
echo "<dependency>"
echo "    <groupId>org.springframework.boot</groupId>"
echo "    <artifactId>spring-boot-starter-data-jpa</artifactId>"
echo "</dependency>"
echo ""
echo "<dependency>"
echo "    <groupId>org.springframework.boot</groupId>"
echo "    <artifactId>spring-boot-starter-web</artifactId>"
echo "</dependency>"
echo ""
echo "<dependency>"
echo "    <groupId>mysql</groupId>"
echo "    <artifactId>mysql-connector-java</artifactId>"
echo "    <version>8.0.33</version>"
echo "</dependency>"
echo ""
echo "<dependency>"
echo "    <groupId>org.projectlombok</groupId>"
echo "    <artifactId>lombok</artifactId>"
echo "    <optional>true</optional>"
echo "</dependency>"
