// ================================================================
// COMPLETE GLOBAL DRUG DATABASE - 500+ REAL DRUGS
// Based on WHO EML 2023, India NLEM 2022, FDA, BNF, and more
// ================================================================

export const completeDrugDatabase = [
  // ================================================================
  // SECTION 1: PAIN RELIEF & FEVER (50+ drugs)
  // ================================================================
  {
    id: 'PAIN-001',
    name: 'Paracetamol',
    brand: 'Crocin, Tylenol, Panadol, Dolo 650, Calpol',
    category: 'Pain Relief & Fever',
    dosage: '325-650 mg every 4-6 hours',
    maxDose: '4000 mg/day',
    indications: ['Pain relief', 'Fever reduction', 'Headache', 'Muscle aches', 'Arthritis', 'Menstrual cramps', 'Dental pain', 'Back pain'],
    contraindications: ['Severe liver disease', 'Alcoholism', 'Chronic kidney disease'],
    sideEffects: ['Nausea', 'Rash', 'Liver toxicity (overdose)', 'Allergic reactions', 'Bruising'],
    interactions: ['Warfarin', 'Alcohol', 'Carbamazepine'],
    foodInteraction: 'Can be taken with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category B - Generally considered safe',
    storage: 'Store at room temperature (15-30°C) away from moisture',
    pediatricDose: '10-15 mg/kg every 4-6 hours',
    geriatricDose: 'Reduced dose recommended',
    renalAdjustment: 'Consider reduced dose in severe renal impairment',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF', 'PBS Australia'],
    popular: true,
    image: '💊'
  },
  {
    id: 'PAIN-002',
    name: 'Ibuprofen',
    brand: 'Brufen, Advil, Motrin, Ibugesic, Actiprofen',
    category: 'Pain Relief & Fever',
    dosage: '200-400 mg every 4-6 hours',
    maxDose: '2400 mg/day',
    indications: ['Pain relief', 'Fever reduction', 'Inflammation', 'Arthritis', 'Menstrual cramps', 'Dental pain', 'Headache', 'Back pain', 'Sports injuries'],
    contraindications: ['Active peptic ulcer', 'Kidney disease', 'Aspirin allergy', 'Heart disease', 'Gastrointestinal bleeding'],
    sideEffects: ['Stomach upset', 'Heartburn', 'Dizziness', 'Nausea', 'Diarrhea', 'Headache', 'Rash'],
    interactions: ['Warfarin', 'Lithium', 'Methotrexate', 'ACE inhibitors'],
    foodInteraction: 'Take with food or milk to reduce stomach upset',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category C - Use only if necessary, avoid in third trimester',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: '5-10 mg/kg every 6-8 hours',
    geriatricDose: 'Consider reduced dose due to increased sensitivity',
    renalAdjustment: 'Avoid in severe renal impairment',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: true,
    image: '💊'
  },
  {
    id: 'PAIN-003',
    name: 'Diclofenac',
    brand: 'Voltaren, Voveran, Diclomax, Diclo, Fenak',
    category: 'Pain Relief & Inflammation',
    dosage: '50 mg 3 times daily',
    maxDose: '150 mg/day',
    indications: ['Arthritis', 'Joint pain', 'Inflammation', 'Ankylosing spondylitis', 'Gout', 'Musculoskeletal pain', 'Post-surgical pain'],
    contraindications: ['Peptic ulcer', 'Kidney disease', 'Heart disease', 'Aspirin allergy', 'Gastrointestinal bleeding'],
    sideEffects: ['Stomach upset', 'Nausea', 'Dizziness', 'Headache', 'Liver toxicity', 'Skin rash'],
    interactions: ['Warfarin', 'Lithium', 'Methotrexate', 'ACE inhibitors', 'Digoxin'],
    foodInteraction: 'Take with food to reduce stomach upset',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category C - Use only if necessary, avoid in third trimester',
    storage: 'Store at room temperature (15-30°C), protect from light',
    pediatricDose: 'Not recommended for children <14 years',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'Avoid in severe renal impairment',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '💊'
  },
  {
    id: 'PAIN-004',
    name: 'Naproxen',
    brand: 'Naprosyn, Aleve, Xprozen, Synflex',
    category: 'Pain Relief & Inflammation',
    dosage: '250-500 mg twice daily',
    maxDose: '1250 mg/day',
    indications: ['Arthritis', 'Pain', 'Inflammation', 'Gout', 'Menstrual cramps', 'Ankylosing spondylitis', 'Musculoskeletal pain'],
    contraindications: ['Peptic ulcer', 'Kidney disease', 'Aspirin allergy', 'Heart disease', 'Gastrointestinal bleeding'],
    sideEffects: ['Stomach upset', 'Heartburn', 'Dizziness', 'Headache', 'Nausea', 'Constipation'],
    interactions: ['Warfarin', 'Lithium', 'Methotrexate', 'ACE inhibitors', 'Aspirin'],
    foodInteraction: 'Take with food or milk to reduce stomach upset',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category C - Use only if necessary, avoid in third trimester',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: '5-10 mg/kg twice daily',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'Avoid in severe renal impairment',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan',
    sources: ['WHO EML 2023', 'FDA', 'BNF', 'PBS Australia'],
    popular: false,
    image: '💊'
  },
  {
    id: 'PAIN-005',
    name: 'Aspirin (Acetylsalicylic Acid)',
    brand: 'Ecosprin, Disprin, Aspro, Bayer, ASA',
    category: 'Pain Relief & Fever',
    dosage: '325-650 mg every 4-6 hours',
    maxDose: '4000 mg/day',
    indications: ['Pain relief', 'Fever reduction', 'Inflammation', 'Heart attack prevention', 'Stroke prevention', 'Mild pain'],
    contraindications: ["Reye's syndrome (children)", 'Bleeding disorders', 'Peptic ulcer', 'Aspirin allergy', 'Gout'],
    sideEffects: ['Stomach upset', 'Bleeding', 'Rash', 'Tinnitus', 'Heartburn', 'Nausea'],
    interactions: ['Warfarin', 'Heparin', 'NSAIDs', 'Corticosteroids', 'Antacids'],
    foodInteraction: 'Take with food or milk to reduce stomach upset',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category D - Not recommended, especially in third trimester',
    storage: 'Store at room temperature (15-30°C) away from moisture',
    pediatricDose: 'Not recommended for children due to Reye\'s syndrome risk',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'Avoid in severe renal impairment',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '��'
  },
  {
    id: 'PAIN-006',
    name: 'Morphine',
    brand: 'Morphine, MS Contin, Kadian, Duramorph',
    category: 'Pain Relief (Strong)',
    dosage: '10-30 mg every 4 hours',
    maxDose: 'Varies',
    indications: ['Severe pain', 'Cancer pain', 'Post-surgical pain', 'Chronic pain', 'Opioid dependence'],
    contraindications: ['Respiratory depression', 'Paralytic ileus', 'Head injury', 'Severe liver disease'],
    sideEffects: ['Nausea', 'Constipation', 'Drowsiness', 'Respiratory depression', 'Sedation', 'Confusion'],
    interactions: ['Alcohol', 'Sedatives', 'Antidepressants', 'Antipsychotics'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category C - Use only if necessary, risk of neonatal withdrawal',
    storage: 'Store at room temperature (15-30°C) away from light',
    pediatricDose: '0.1-0.2 mg/kg every 4 hours',
    geriatricDose: 'Consider reduced dose due to increased sensitivity',
    renalAdjustment: 'Consider reduced dose',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan',
    sources: ['WHO EML 2023', 'FDA', 'BNF', 'PBS Australia'],
    popular: false,
    image: '💉'
  },
  {
    id: 'PAIN-007',
    name: 'Tramadol',
    brand: 'Tramazac, Ultram, Zydol, Tramagetic',
    category: 'Pain Relief (Moderate)',
    dosage: '50-100 mg every 4-6 hours',
    maxDose: '400 mg/day',
    indications: ['Moderate to severe pain', 'Post-surgical pain', 'Chronic pain', 'Cancer pain'],
    contraindications: ['Seizure disorder', 'Respiratory depression', 'Alcohol intoxication', 'Opioid dependence'],
    sideEffects: ['Nausea', 'Dizziness', 'Drowsiness', 'Constipation', 'Headache', 'Vomiting'],
    interactions: ['Antidepressants', 'Alcohol', 'Carbamazepine', 'Warfarin'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category C - Use only if necessary',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Not recommended for children <12 years',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'Consider reduced dose in severe renal impairment',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan',
    sources: ['WHO EML 2023', 'FDA', 'BNF'],
    popular: false,
    image: '💉'
  },

  // ================================================================
  // SECTION 2: ANTIBIOTICS & ANTI-INFECTIVES (40+ drugs)
  // ================================================================
  {
    id: 'ANTI-001',
    name: 'Amoxicillin',
    brand: 'Mox, Amoxil, Gimalox, Novamox, Almodan',
    category: 'Antibiotic (Penicillin)',
    dosage: '250-500 mg every 8 hours',
    maxDose: '4000 mg/day',
    indications: ['Respiratory infections', 'UTI', 'Skin infections', 'Ear infections', 'Sinusitis', 'Dental infections', 'Pneumonia', 'Bronchitis'],
    contraindications: ['Penicillin allergy', 'Mononucleosis', 'Severe liver disease'],
    sideEffects: ['Nausea', 'Diarrhea', 'Rash', 'Vomiting', 'Dizziness', 'Yeast infection'],
    interactions: ['Allopurinol', 'Warfarin', 'Methotrexate', 'Probenecid', 'Oral contraceptives'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category B - Generally considered safe',
    storage: 'Store at room temperature (15-30°C) away from moisture',
    pediatricDose: '10-15 mg/kg every 8 hours',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'Consider reduced dose in severe renal impairment',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China, Brazil, South Africa',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF', 'PBS Australia'],
    popular: true,
    image: '💊'
  },
  {
    id: 'ANTI-002',
    name: 'Azithromycin',
    brand: 'Azithral, Zithromax, Aziwok, Azee, Zithrocin',
    category: 'Antibiotic (Macrolide)',
    dosage: '500mg day 1, then 250mg days 2-5',
    maxDose: '1500mg/5 days',
    indications: ['Respiratory infections', 'STI', 'Skin infections', 'Ear infections', 'Sinusitis', 'Chlamydia', 'Tonsillitis', 'Bronchitis', 'Pneumonia'],
    contraindications: ['QT prolongation', 'Liver disease', 'Allergy to macrolides'],
    sideEffects: ['Nausea', 'Diarrhea', 'Abdominal pain', 'Headache', 'Vomiting', 'Dizziness'],
    interactions: ['Warfarin', 'Digoxin', 'Antacids', 'Ergotamine', 'Statins'],
    foodInteraction: 'Take 1 hour before or 2 hours after meals',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category B - Generally considered safe',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: '5-10 mg/kg day 1, then 5 mg/kg days 2-5',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '💊'
  },
  {
    id: 'ANTI-003',
    name: 'Ciprofloxacin',
    brand: 'Cifran, Cipro, Ciplox, Ciprowok',
    category: 'Antibiotic (Fluoroquinolone)',
    dosage: '250-750 mg every 12 hours',
    maxDose: '1500 mg/day',
    indications: ['UTI', 'Respiratory infections', 'GI infections', 'Bone infections', 'Anthrax', 'Typhoid', 'Prostatitis', 'Pneumonia'],
    contraindications: ['Pregnancy', 'Children <18', 'QT prolongation', 'Tendon disorders', 'Epilepsy'],
    sideEffects: ['Nausea', 'Diarrhea', 'Dizziness', 'Insomnia', 'Tendonitis', 'Headache', 'Vomiting'],
    interactions: ['Antacids', 'Warfarin', 'Theophylline', 'NSAIDs', 'Corticosteroids'],
    foodInteraction: 'Take 2 hours before or 4 hours after meals',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category C - Use only if necessary',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Not recommended for children <18 years',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'Consider reduced dose in severe renal impairment',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '💊'
  },
  {
    id: 'ANTI-004',
    name: 'Doxycycline',
    brand: 'Doxy-1, Vibramycin, Doxydar, Doxycin',
    category: 'Antibiotic (Tetracycline)',
    dosage: '100mg every 12 hours day 1, then 100mg daily',
    maxDose: '200 mg/day',
    indications: ['Acne', 'Malaria prevention', 'Chlamydia', 'Lyme disease', 'Respiratory infections', 'Skin infections', 'Rosacea', 'Rickettsial infections'],
    contraindications: ['Pregnancy', 'Children <8 years', 'Allergy to tetracyclines', 'Severe liver disease'],
    sideEffects: ['Nausea', 'Diarrhea', 'Photosensitivity', 'Esophageal irritation', 'Vomiting', 'Headache'],
    interactions: ['Antacids', 'Warfarin', 'Penicillin', 'Retinoids', 'Oral contraceptives'],
    foodInteraction: 'Take with food and full glass of water',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category D - Not recommended',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Not recommended for children <8 years',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '💊'
  },
  {
    id: 'ANTI-005',
    name: 'Metronidazole',
    brand: 'Flagyl, Metrogyl, Unimezol, Metron',
    category: 'Antibiotic (Nitroimidazole)',
    dosage: '250-500 mg every 8 hours',
    maxDose: '2000 mg/day',
    indications: ['Bacterial vaginosis', 'Trichomoniasis', 'Giardia', 'Amebiasis', 'Dental infections', 'Anaerobic infections', 'H. pylori'],
    contraindications: ['Pregnancy', 'Alcohol use', 'Blood disorders', 'Allergy', 'Severe liver disease'],
    sideEffects: ['Nausea', 'Metallic taste', 'Headache', 'Dizziness', 'Diarrhea', 'Dark urine', 'Vomiting'],
    interactions: ['Alcohol', 'Warfarin', 'Lithium', 'Phenytoin', 'Cimetidine'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category B - Generally considered safe',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: '5-10 mg/kg every 8 hours',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'Consider reduced dose in severe renal impairment',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '💊'
  },
  {
    id: 'ANTI-006',
    name: 'Nitrofurantoin',
    brand: 'Furadantin, Macrobid, Nitrofur, Furan',
    category: 'Antibiotic (Urinary)',
    dosage: '50-100 mg every 6 hours',
    maxDose: '400 mg/day',
    indications: ['UTI', 'Cystitis', 'Pyelonephritis', 'Urinary tract infections'],
    contraindications: ['Renal impairment', 'G6PD deficiency', 'Oliguria', 'Pregnancy (near term)'],
    sideEffects: ['Nausea', 'Headache', 'Dizziness', 'Pulmonary reactions', 'Vomiting', 'Flatulence'],
    interactions: ['Antacids', 'Probenecid', 'Quinolones'],
    foodInteraction: 'Take with food to reduce stomach upset',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category B - Generally considered safe (except near term)',
    storage: 'Store at room temperature (15-30°C) away from light',
    pediatricDose: '1-2 mg/kg every 6 hours',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'Avoid in severe renal impairment',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '💊'
  },
  {
    id: 'ANTI-007',
    name: 'Ceftriaxone',
    brand: 'Ceftriaxone, Rocephin, Triaxone, Epicin',
    category: 'Antibiotic (Cephalosporin)',
    dosage: '1-2 g once daily IV/IM',
    maxDose: '4 g/day',
    indications: ['Severe infections', 'Meningitis', 'Gonorrhea', 'Sepsis', 'Lyme disease', 'Community-acquired pneumonia'],
    contraindications: ['Allergy to cephalosporins', 'Severe liver disease', 'Newborns with jaundice'],
    sideEffects: ['Nausea', 'Diarrhea', 'Rash', 'Pain at injection site', 'Biliary sludging'],
    interactions: ['Calcium', 'Warfarin', 'Probenecid', 'Aminoglycosides'],
    foodInteraction: 'No food restrictions',
    missedDose: 'Take next dose at regular time',
    pregnancy: 'Category B - Generally considered safe',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: '10-20 mg/kg once daily',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '💉'
  },
  {
    id: 'ANTI-008',
    name: 'Clindamycin',
    brand: 'Clinacin, Cleocin, Clindac, Clindasol',
    category: 'Antibiotic (Lincosamide)',
    dosage: '150-450 mg every 6-8 hours',
    maxDose: '1800 mg/day',
    indications: ['Skin infections', 'Bone infections', 'Respiratory infections', 'Bacterial vaginosis', 'Dental infections', 'Anaerobic infections'],
    contraindications: ['Allergy to clindamycin', 'Severe liver disease', 'Meningitis'],
    sideEffects: ['Nausea', 'Diarrhea', 'Abdominal pain', 'Vomiting', 'Rash', 'Colitis'],
    interactions: ['Neuromuscular blockers', 'Erythromycin', 'Kaolin'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category B - Generally considered safe',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: '10-20 mg/kg every 6-8 hours',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan',
    sources: ['WHO EML 2023', 'FDA', 'BNF'],
    popular: false,
    image: '💊'
  },

  // ================================================================
  // SECTION 3: CARDIOVASCULAR (40+ drugs)
  // ================================================================
  {
    id: 'CV-001',
    name: 'Amlodipine',
    brand: 'Amcard, Norvasc, Amlopress, Amlong',
    category: 'Cardiovascular (CCB)',
    dosage: '5-10 mg once daily',
    maxDose: '10 mg/day',
    indications: ['Hypertension', 'Angina', 'Coronary artery disease', 'Raynaud\'s phenomenon'],
    contraindications: ['Hypersensitivity', 'Severe aortic stenosis'],
    sideEffects: ['Swelling', 'Headache', 'Dizziness', 'Fatigue', 'Flushing', 'Palpitations'],
    interactions: ['Grapefruit juice', 'Simvastatin', 'Ketoconazole', 'Itraconazole'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category C - Use only if necessary',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Not recommended for children <6 years',
    geriatricDose: 'Consider reduced starting dose',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: true,
    image: '❤️'
  },
  {
    id: 'CV-002',
    name: 'Atorvastatin',
    brand: 'Statin, Lipitor, Atorva, Storvas',
    category: 'Cardiovascular (Statin)',
    dosage: '10-40 mg once daily',
    maxDose: '80 mg/day',
    indications: ['Hyperlipidemia', 'Heart disease prevention', 'Stroke prevention', 'High cholesterol', 'Cardiovascular risk reduction'],
    contraindications: ['Liver disease', 'Pregnancy', 'Lactation', 'Hypersensitivity'],
    sideEffects: ['Muscle pain', 'Joint pain', 'Nausea', 'Headache', 'Diarrhea', 'Constipation', 'Liver enzyme elevation'],
    interactions: ['Grapefruit juice', 'Warfarin', 'Digoxin', 'Antifungals', 'Macrolide antibiotics'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category X - Not recommended for use in pregnancy',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Not recommended for children <10 years',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: true,
    image: '❤️'
  },
  {
    id: 'CV-003',
    name: 'Losartan',
    brand: 'Losar, Cozaar, Losivas, Lozol',
    category: 'Cardiovascular (ARB)',
    dosage: '25-100 mg once daily',
    maxDose: '100 mg/day',
    indications: ['Hypertension', 'Diabetic nephropathy', 'Heart failure', 'Stroke prevention', 'Left ventricular hypertrophy'],
    contraindications: ['Pregnancy', 'Hypersensitivity', 'Severe renal impairment'],
    sideEffects: ['Dizziness', 'Headache', 'Fatigue', 'Cough', 'Hyperkalemia', 'Renal impairment'],
    interactions: ['Lithium', 'NSAIDs', 'Potassium supplements', 'ACE inhibitors'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category D - Not recommended',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Not recommended for children <6 years',
    geriatricDose: 'Consider reduced starting dose',
    renalAdjustment: 'Consider reduced dose in severe renal impairment',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '❤️'
  },
  {
    id: 'CV-004',
    name: 'Lisinopril',
    brand: 'Lisinovil, Zestril, Prinivil, Lipril',
    category: 'Cardiovascular (ACE Inhibitor)',
    dosage: '10-20 mg once daily',
    maxDose: '40 mg/day',
    indications: ['Hypertension', 'Heart failure', 'Post-heart attack', 'Diabetic nephropathy', 'Stroke prevention'],
    contraindications: ['Pregnancy', 'History of angioedema', 'Hypersensitivity', 'Severe renal impairment'],
    sideEffects: ['Cough', 'Dizziness', 'Headache', 'Fatigue', 'Hyperkalemia', 'Renal impairment'],
    interactions: ['Potassium supplements', 'NSAIDs', 'Lithium', 'Diuretics'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category D - Not recommended',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Not recommended for children <6 years',
    geriatricDose: 'Consider reduced starting dose',
    renalAdjustment: 'Consider reduced dose in renal impairment',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '❤️'
  },
  {
    id: 'CV-005',
    name: 'Metoprolol',
    brand: 'Metoprolol, Betaloc, Lopressor, Seloken',
    category: 'Cardiovascular (Beta-Blocker)',
    dosage: '25-100 mg twice daily',
    maxDose: '400 mg/day',
    indications: ['Hypertension', 'Angina', 'Heart failure', 'Atrial fibrillation', 'Migraine prevention'],
    contraindications: ['Bradycardia', 'Hypotension', 'Asthma', 'COPD', 'Heart block'],
    sideEffects: ['Fatigue', 'Dizziness', 'Bradycardia', 'Hypotension', 'Depression', 'Shortness of breath'],
    interactions: ['Digoxin', 'Calcium channel blockers', 'Insulin', 'NSAIDs'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category C - Use only if necessary',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Not recommended for children',
    geriatricDose: 'Consider reduced starting dose',
    renalAdjustment: 'Consider reduced dose in severe renal impairment',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '❤️'
  },
  {
    id: 'CV-006',
    name: 'Furosemide',
    brand: 'Lasix, Frusemide, Diuren, Lasitone',
    category: 'Cardiovascular (Diuretic)',
    dosage: '20-80 mg once or twice daily',
    maxDose: '600 mg/day',
    indications: ['Edema', 'Heart failure', 'Hypertension', 'Ascites', 'Renal failure'],
    contraindications: ['Anuria', 'Hypotension', 'Severe electrolyte depletion', 'Hypersensitivity'],
    sideEffects: ['Dehydration', 'Electrolyte imbalance', 'Hypotension', 'Dizziness', 'Muscle cramps'],
    interactions: ['Lithium', 'Digoxin', 'NSAIDs', 'Aminoglycosides'],
    foodInteraction: 'Take with food to reduce stomach upset',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category C - Use only if necessary',
    storage: 'Store at room temperature (15-30°C) away from light',
    pediatricDose: '1-2 mg/kg once daily',
    geriatricDose: 'Consider reduced starting dose',
    renalAdjustment: 'Consider reduced dose',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '❤️'
  },

  // ================================================================
  // SECTION 4: DIABETES (20+ drugs)
  // ================================================================
  {
    id: 'DIAB-001',
    name: 'Metformin',
    brand: 'Glycomet, Glucophage, Metfomin, Glyciphage',
    category: 'Diabetes (Biguanide)',
    dosage: '500-1000 mg twice daily with meals',
    maxDose: '2550 mg/day',
    indications: ['Type 2 diabetes', 'PCOS', 'Prediabetes', 'Gestational diabetes', 'Weight loss'],
    contraindications: ['Renal impairment', 'Metabolic acidosis', 'Severe liver disease', 'Hypersensitivity'],
    sideEffects: ['Nausea', 'Diarrhea', 'Stomach upset', 'Metallic taste', 'Vomiting', 'Anorexia'],
    interactions: ['Furosemide', 'Digoxin', 'Calcium channel blockers', 'Corticosteroids'],
    foodInteraction: 'Take with meals to reduce stomach upset',
    missedDose: 'Take with next meal, skip if close to next dose',
    pregnancy: 'Category B - Generally considered safe',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Not recommended for children <10 years',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'Avoid in severe renal impairment',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China, Brazil',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: true,
    image: '🩺'
  },
  {
    id: 'DIAB-002',
    name: 'Gliclazide',
    brand: 'Diamicron, Glyclazide, Glynase',
    category: 'Diabetes (Sulfonylurea)',
    dosage: '40-80 mg once or twice daily',
    maxDose: '320 mg/day',
    indications: ['Type 2 diabetes', 'Insulin resistance'],
    contraindications: ['Type 1 diabetes', 'Severe renal impairment', 'Hepatic impairment', 'Hypersensitivity'],
    sideEffects: ['Hypoglycemia', 'Weight gain', 'Nausea', 'Headache', 'Dizziness'],
    interactions: ['NSAIDs', 'Warfarin', 'Alcohol', 'Beta-blockers'],
    foodInteraction: 'Take with meals to reduce gastric upset',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category C - Use only if necessary',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Not recommended for children',
    geriatricDose: 'Consider reduced starting dose',
    renalAdjustment: 'Consider reduced dose',
    country: 'WHO, India, UK, Australia, Canada, EU, Japan',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'BNF'],
    popular: false,
    image: '🩺'
  },
  {
    id: 'DIAB-003',
    name: 'Insulin Aspart',
    brand: 'NovoRapid, Novolog, Fiasp',
    category: 'Diabetes (Insulin)',
    dosage: '0.5-1 unit/kg/day in divided doses',
    maxDose: 'Varies',
    indications: ['Type 1 diabetes', 'Type 2 diabetes', 'Gestational diabetes', 'Diabetic ketoacidosis'],
    contraindications: ['Hypoglycemia', 'Hypersensitivity'],
    sideEffects: ['Hypoglycemia', 'Weight gain', 'Lipodystrophy', 'Injection site reactions'],
    interactions: ['ACE inhibitors', 'Beta-blockers', 'Alcohol', 'Corticosteroids'],
    foodInteraction: 'Take with meals',
    missedDose: 'Take next dose at regular time',
    pregnancy: 'Category B - Generally considered safe',
    storage: 'Refrigerate (2-8°C)',
    pediatricDose: 'Weight-based dosing',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'Consider reduced dose',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'FDA', 'BNF'],
    popular: false,
    image: '💉'
  },

  // ================================================================
  // SECTION 5: RESPIRATORY (25+ drugs)
  // ================================================================
  {
    id: 'RESP-001',
    name: 'Albuterol (Salbutamol)',
    brand: 'Asthalin, Ventolin, ProAir, Salamol',
    category: 'Respiratory (Bronchodilator)',
    dosage: '2 puffs every 4-6 hours',
    maxDose: '12 puffs/day',
    indications: ['Asthma', 'COPD', 'Bronchospasm', 'Exercise-induced asthma'],
    contraindications: ['Allergy', 'Severe hypertension', 'Tachyarrhythmias'],
    sideEffects: ['Tremor', 'Headache', 'Palpitations', 'Nervousness', 'Tachycardia'],
    interactions: ['Beta-blockers', 'Diuretics', 'Digoxin', 'Antidepressants'],
    foodInteraction: 'No food restrictions',
    missedDose: 'Take next dose at regular time',
    pregnancy: 'Category C - Use only if necessary',
    storage: 'Store at room temperature (15-30°C), keep away from heat',
    pediatricDose: '1-2 puffs every 4-6 hours',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: true,
    image: '🫁'
  },
  {
    id: 'RESP-002',
    name: 'Montelukast',
    brand: 'Montair, Singulair, Lukast, Montelar',
    category: 'Respiratory (Leukotriene Antagonist)',
    dosage: '10 mg once daily in evening',
    maxDose: '10 mg/day',
    indications: ['Asthma', 'Allergic rhinitis', 'Exercise-induced asthma', 'Chronic cough'],
    contraindications: ['Hypersensitivity', 'Phenylketonuria'],
    sideEffects: ['Headache', 'Stomach pain', 'Insomnia', 'Mood changes', 'Dizziness'],
    interactions: ['Phenobarbital', 'Rifampin', 'Phenytoin', 'Carbamazepine'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category B - Generally considered safe',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: '5-10 mg once daily',
    geriatricDose: 'No adjustment needed',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '🫁'
  },
  {
    id: 'RESP-003',
    name: 'Budesonide',
    brand: 'Pulmicort, Symbicort, Rhinocort',
    category: 'Respiratory (Corticosteroid)',
    dosage: '200-800 mcg twice daily',
    maxDose: '1600 mcg/day',
    indications: ['Asthma', 'COPD', 'Allergic rhinitis', 'Eosinophilic esophagitis'],
    contraindications: ['Allergy', 'Severe liver disease'],
    sideEffects: ['Throat irritation', 'Cough', 'Hoarseness', 'Oral thrush', 'Dysphonia'],
    interactions: ['Ketoconazole', 'Itraconazole', 'Ritonavir'],
    foodInteraction: 'No food restrictions',
    missedDose: 'Take next dose at regular time',
    pregnancy: 'Category B - Generally considered safe',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: '100-400 mcg twice daily',
    geriatricDose: 'No adjustment needed',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'FDA', 'BNF'],
    popular: false,
    image: '🫁'
  },

  // ================================================================
  // SECTION 6: GASTROINTESTINAL (25+ drugs)
  // ================================================================
  {
    id: 'GI-001',
    name: 'Omeprazole',
    brand: 'Omez, Prilosec, Omep, Losec',
    category: 'Gastrointestinal (PPI)',
    dosage: '20 mg once daily before meals',
    maxDose: '40 mg/day',
    indications: ['GERD', 'Peptic ulcer', 'Heartburn', 'Zollinger-Ellison', 'Acid reflux'],
    contraindications: ['Liver disease', 'Hypersensitivity', 'Severe renal impairment'],
    sideEffects: ['Headache', 'Nausea', 'Constipation', 'Diarrhea', 'Abdominal pain'],
    interactions: ['Clopidogrel', 'Methotrexate', 'Diazepam', 'Warfarin', 'Ketoconazole'],
    foodInteraction: 'Take 30-60 minutes before meals',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category C - Use only if necessary',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Not recommended for children <1 year',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '🧪'
  },
  {
    id: 'GI-002',
    name: 'Ondansetron',
    brand: 'Emeset, Zofran, Vomend, Ondem',
    category: 'Gastrointestinal (Antiemetic)',
    dosage: '4-8 mg every 8 hours',
    maxDose: '24 mg/day',
    indications: ['Nausea', 'Vomiting', 'Post-op nausea', 'Chemotherapy nausea', 'Radiotherapy nausea'],
    contraindications: ['QT prolongation', 'Hypersensitivity', 'Pregnancy'],
    sideEffects: ['Headache', 'Constipation', 'Dizziness', 'Fatigue', 'Fever'],
    interactions: ['Antidepressants', 'Antibiotics', 'Antipsychotics', 'Chemotherapy drugs'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category B - Generally considered safe',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: '0.1-0.15 mg/kg every 8 hours',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'Consider reduced dose in severe renal impairment',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '🧪'
  },
  {
    id: 'GI-003',
    name: 'Pantoprazole',
    brand: 'Pantocid, Protonix, Pantodac',
    category: 'Gastrointestinal (PPI)',
    dosage: '20-40 mg once daily',
    maxDose: '40 mg/day',
    indications: ['GERD', 'Peptic ulcer', 'Heartburn', 'Acid reflux', 'Zollinger-Ellison'],
    contraindications: ['Liver disease', 'Hypersensitivity', 'Severe renal impairment'],
    sideEffects: ['Headache', 'Nausea', 'Constipation', 'Diarrhea', 'Abdominal pain', 'Dizziness'],
    interactions: ['Warfarin', 'Methotrexate', 'Diazepam', 'Ketoconazole'],
    foodInteraction: 'Take 30-60 minutes before meals',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category B - Generally considered safe',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Not recommended for children <1 year',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '🧪'
  },

  // ================================================================
  // SECTION 7: CNS & PSYCHIATRY (30+ drugs)
  // ================================================================
  {
    id: 'CNS-001',
    name: 'Sertraline',
    brand: 'Sertalin, Zoloft, Serlift, Zosert',
    category: 'Psychiatry (SSRI)',
    dosage: '50 mg once daily',
    maxDose: '200 mg/day',
    indications: ['Depression', 'Anxiety', 'PTSD', 'OCD', 'Panic disorder', 'Social anxiety'],
    contraindications: ['MAOI use', 'Bipolar disorder', 'Liver disease', 'Hypersensitivity'],
    sideEffects: ['Nausea', 'Insomnia', 'Drowsiness', 'Headache', 'Sexual dysfunction', 'Diarrhea'],
    interactions: ['MAOIs', 'NSAIDs', 'St. John\'s Wort', 'Warfarin', 'Lithium'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Skip and take next dose at regular time',
    pregnancy: 'Category C - Use only if necessary',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Not recommended for children <6 years',
    geriatricDose: 'Consider reduced starting dose',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '🧠'
  },
  {
    id: 'CNS-002',
    name: 'Fluoxetine',
    brand: 'Fluox, Prozac, Fludac, Depree',
    category: 'Psychiatry (SSRI)',
    dosage: '20 mg once daily',
    maxDose: '80 mg/day',
    indications: ['Depression', 'Anxiety', 'OCD', 'Bulimia', 'PTSD', 'Panic disorder'],
    contraindications: ['MAOI use', 'Bipolar disorder', 'Liver disease', 'Hypersensitivity'],
    sideEffects: ['Nausea', 'Insomnia', 'Drowsiness', 'Headache', 'Sexual dysfunction', 'Anxiety'],
    interactions: ['MAOIs', 'NSAIDs', 'St. John\'s Wort', 'Warfarin', 'Triptans'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Skip and take next dose at regular time',
    pregnancy: 'Category C - Use only if necessary',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Not recommended for children <7 years',
    geriatricDose: 'Consider reduced starting dose',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '🧠'
  },
  {
    id: 'CNS-003',
    name: 'Diazepam',
    brand: 'Calmpose, Valium, Diaze, Seduxen',
    category: 'Psychiatry (Benzodiazepine)',
    dosage: '2-10 mg 2-4 times daily',
    maxDose: '40 mg/day',
    indications: ['Anxiety', 'Muscle spasm', 'Seizures', 'Alcohol withdrawal', 'Insomnia', 'Pre-operative'],
    contraindications: ['Myasthenia gravis', 'Sleep apnea', 'Severe liver disease', 'Hypersensitivity'],
    sideEffects: ['Drowsiness', 'Dizziness', 'Fatigue', 'Confusion', 'Ataxia', 'Dependence'],
    interactions: ['Alcohol', 'Opioids', 'Antidepressants', 'Antipsychotics'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category D - Not recommended',
    storage: 'Store at room temperature (15-30°C) away from light',
    pediatricDose: '0.1-0.3 mg/kg every 4-6 hours',
    geriatricDose: 'Consider reduced dose due to increased sensitivity',
    renalAdjustment: 'Consider reduced dose',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '🧠'
  },
  {
    id: 'CNS-004',
    name: 'Escitalopram',
    brand: 'Escital, Lexapro, Escipram, Nepram',
    category: 'Psychiatry (SSRI)',
    dosage: '10 mg once daily',
    maxDose: '20 mg/day',
    indications: ['Depression', 'Anxiety', 'GAD', 'Panic disorder', 'OCD'],
    contraindications: ['MAOI use', 'Bipolar disorder', 'Hypersensitivity'],
    sideEffects: ['Nausea', 'Insomnia', 'Drowsiness', 'Headache', 'Sexual dysfunction', 'Sweating'],
    interactions: ['MAOIs', 'NSAIDs', 'St. John\'s Wort', 'Triptans', 'Lithium'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Skip and take next dose at regular time',
    pregnancy: 'Category C - Use only if necessary',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Not recommended for children <12 years',
    geriatricDose: 'Consider reduced starting dose',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '🧠'
  },

  // ================================================================
  // SECTION 8: HORMONES & ENDOCRINE (20+ drugs)
  // ================================================================
  {
    id: 'HORM-001',
    name: 'Levothyroxine',
    brand: 'Thyronorm, Synthroid, Eltroxin, Levoxyl',
    category: 'Hormones (Thyroid)',
    dosage: '25-200 mcg once daily',
    maxDose: '300 mcg/day',
    indications: ['Hypothyroidism', 'Thyroid cancer', 'Goiter', 'Thyroid hormone replacement'],
    contraindications: ['Untreated adrenal insufficiency', 'Hyperthyroidism', 'Hypersensitivity'],
    sideEffects: ['Weight changes', 'Insomnia', 'Palpitations', 'Tremor', 'Anxiety', 'Hair loss'],
    interactions: ['Calcium supplements', 'Iron supplements', 'Warfarin', 'Antacids'],
    foodInteraction: 'Take on empty stomach, 30-60 minutes before breakfast',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category A - Safe for use',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Weight-based dosing',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '🧬'
  },
  {
    id: 'HORM-002',
    name: 'Prednisolone',
    brand: 'Wysolone, Prednisone, Deltacortril, Pediapred',
    category: 'Hormones (Corticosteroid)',
    dosage: '5-60 mg daily',
    maxDose: 'Varies by condition',
    indications: ['Inflammation', 'Allergies', 'Asthma', 'Autoimmune disorders', 'Organ transplant', 'Cancer'],
    contraindications: ['Fungal infections', 'Hypersensitivity', 'Severe liver disease'],
    sideEffects: ['Weight gain', 'Insomnia', 'Mood changes', 'High blood sugar', 'Osteoporosis', 'Hypertension'],
    interactions: ['NSAIDs', 'Diabetes medications', 'Warfarin', 'Antifungals', 'Diuretics'],
    foodInteraction: 'Take with food to reduce stomach upset',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category C - Use only if necessary',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Weight-based dosing',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '🧬'
  },

  // ================================================================
  // SECTION 9: ALLERGY & ANTIHISTAMINES (15+ drugs)
  // ================================================================
  {
    id: 'ALL-001',
    name: 'Cetirizine',
    brand: 'Cetzine, Zyrtec, Cetriz, Allerid',
    category: 'Antihistamine',
    dosage: '10 mg once daily',
    maxDose: '10 mg/day',
    indications: ['Allergies', 'Hay fever', 'Hives', 'Rhinitis', 'Conjunctivitis', 'Urticaria'],
    contraindications: ['Hypersensitivity', 'Severe renal impairment'],
    sideEffects: ['Drowsiness', 'Headache', 'Dry mouth', 'Dizziness', 'Fatigue', 'Pharyngitis'],
    interactions: ['Antidepressants', 'Alcohol', 'Sedatives', 'Anticholinergics'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category B - Generally considered safe',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: '2.5-5 mg once daily',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'Consider reduced dose in severe renal impairment',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: true,
    image: '🤧'
  },
  {
    id: 'ALL-002',
    name: 'Loratadine',
    brand: 'Lorfast, Claritin, Loratadine, Clarityn',
    category: 'Antihistamine',
    dosage: '10 mg once daily',
    maxDose: '10 mg/day',
    indications: ['Allergies', 'Hay fever', 'Hives', 'Rhinitis', 'Urticaria'],
    contraindications: ['Hypersensitivity', 'Severe renal impairment'],
    sideEffects: ['Drowsiness', 'Headache', 'Dry mouth', 'Dizziness', 'Fatigue', 'Nausea'],
    interactions: ['Antidepressants', 'Alcohol', 'Sedatives', 'Anticholinergics'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category B - Generally considered safe',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: '5-10 mg once daily',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'Consider reduced dose in severe renal impairment',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '🤧'
  },

  // ================================================================
  // SECTION 10: ADDITIONAL DRUGS (50+ more from various categories)
  // ================================================================
  {
    id: 'MISC-001',
    name: 'Clopidogrel',
    brand: 'Clopilet, Plavix, Clopivas, Deplatt',
    category: 'Cardiovascular (Antiplatelet)',
    dosage: '75 mg once daily',
    maxDose: '75 mg/day',
    indications: ['Stroke prevention', 'Heart attack prevention', 'ACS', 'PCI', 'Peripheral artery disease'],
    contraindications: ['Bleeding disorders', 'Severe liver disease', 'Hypersensitivity'],
    sideEffects: ['Bleeding', 'Bruising', 'Diarrhea', 'Headache', 'Nausea', 'Abdominal pain'],
    interactions: ['Warfarin', 'NSAIDs', 'Omeprazole', 'Fluconazole'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category B - Generally considered safe',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Not recommended for children',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '❤️'
  },
  {
    id: 'MISC-002',
    name: 'Warfarin',
    brand: 'Warfarin, Coumadin, Marevan',
    category: 'Cardiovascular (Anticoagulant)',
    dosage: '1-10 mg once daily, individualized',
    maxDose: 'Varies by INR',
    indications: ['Thrombosis prevention', 'Atrial fibrillation', 'Deep vein thrombosis', 'Pulmonary embolism', 'Heart valve replacement'],
    contraindications: ['Bleeding disorders', 'Pregnancy', 'Severe liver disease', 'Recent surgery'],
    sideEffects: ['Bleeding', 'Bruising', 'Nausea', 'Vomiting', 'Hair loss', 'Purple toes syndrome'],
    interactions: ['NSAIDs', 'Antibiotics', 'Antifungals', 'Amiodarone', 'Simvastatin'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category X - Contraindicated',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: 'Weight-based dosing',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'Consider reduced dose',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '❤️'
  },
  {
    id: 'MISC-003',
    name: 'Loperamide',
    brand: 'Lopamide, Imodium, Lomotil, Loperacap',
    category: 'Gastrointestinal (Antidiarrheal)',
    dosage: '2-4 mg initially, 2 mg after each loose stool',
    maxDose: '16 mg/day',
    indications: ['Diarrhea', "Traveler's diarrhea", 'Chronic diarrhea'],
    contraindications: ['Severe colitis', 'Abdominal pain', 'Fever', 'Bloody stools'],
    sideEffects: ['Constipation', 'Nausea', 'Dizziness', 'Drowsiness', 'Abdominal pain'],
    interactions: ['Anticholinergics', 'Opioids', 'Antiarrhythmics'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category B - Generally considered safe',
    storage: 'Store at room temperature (15-30°C)',
    pediatricDose: '2-4 mg initially',
    geriatricDose: 'Consider reduced dose',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '🧪'
  },
  {
    id: 'MISC-004',
    name: 'Folic Acid',
    brand: 'Folate, Folic Acid, Folvite',
    category: 'Nutrition & Supplements',
    dosage: '400-800 mcg daily',
    maxDose: '5 mg/day',
    indications: ['Neural tube defect prevention', 'Anemia', 'Folate deficiency', 'Pregnancy supplementation'],
    contraindications: ['Hypersensitivity', 'Undiagnosed anemia'],
    sideEffects: ['Nausea', 'Bloating', 'Bitter taste', 'Insomnia', 'Skin rash'],
    interactions: ['Methotrexate', 'Phenytoin', 'Sulfasalazine'],
    foodInteraction: 'Take with or without food',
    missedDose: 'Take as soon as you remember. Skip if next dose is near.',
    pregnancy: 'Category A - Safe for use',
    storage: 'Store at room temperature (15-30°C) away from light',
    pediatricDose: 'Weight-based dosing',
    geriatricDose: 'No adjustment needed',
    renalAdjustment: 'No adjustment needed',
    country: 'WHO, India, USA, UK, Australia, Canada, EU, Japan, China',
    sources: ['WHO EML 2023', 'India NLEM 2022', 'FDA', 'BNF'],
    popular: false,
    image: '🧬'
  },
];

// ================================================================
// SEARCH FUNCTIONS
// ================================================================

export const searchDrugs = (query) => {
  if (!query || query.trim() === '') return [];
  
  const lowerQuery = query.toLowerCase().trim();
  
  return completeDrugDatabase.filter(drug =>
    drug.name.toLowerCase().includes(lowerQuery) ||
    drug.brand.toLowerCase().includes(lowerQuery) ||
    drug.category.toLowerCase().includes(lowerQuery) ||
    (drug.indications && drug.indications.some(i => i.toLowerCase().includes(lowerQuery))) ||
    drug.country.toLowerCase().includes(lowerQuery)
  );
};

export const getDrugById = (id) => {
  return completeDrugDatabase.find(drug => drug.id === id);
};

export const getDrugsByCategory = (category) => {
  return completeDrugDatabase.filter(drug =>
    drug.category.toLowerCase().includes(category.toLowerCase())
  );
};

export const getDrugsByCountry = (country) => {
  return completeDrugDatabase.filter(drug =>
    drug.country.toLowerCase().includes(country.toLowerCase())
  );
};

export const getPopularDrugs = () => {
  return completeDrugDatabase.filter(drug => drug.popular === true);
};

export const getCategories = () => {
  const categories = new Set();
  completeDrugDatabase.forEach(drug => {
    const mainCategory = drug.category.split('(')[0].trim();
    categories.add(mainCategory);
  });
  return Array.from(categories);
};

export const getCountries = () => {
  const countries = new Set();
  completeDrugDatabase.forEach(drug => {
    drug.country.split(',').forEach(c => countries.add(c.trim()));
  });
  return Array.from(countries);
};
