// 200+ Drug Database - Complete
export const drugDatabase = [
  // ============================================
  // PAIN RELIEF (25 drugs)
  // ============================================
  { id: 1, name: 'Paracetamol', brand: 'Crocin, Tylenol', category: 'Pain Relief', dosage: '325-650 mg every 4-6 hours', price: 4.99, indications: ['Pain relief', 'Fever', 'Headache', 'Muscle aches'], sideEffects: ['Nausea', 'Rash', 'Liver damage (overdose)'], image: '💊', rating: 4.5 },
  { id: 2, name: 'Ibuprofen', brand: 'Brufen, Advil', category: 'Pain Relief', dosage: '200-400 mg every 4-6 hours', price: 8.50, indications: ['Pain relief', 'Fever', 'Inflammation', 'Arthritis'], sideEffects: ['Stomach upset', 'Heartburn', 'Nausea'], image: '💊', rating: 4.6 },
  { id: 3, name: 'Diclofenac', brand: 'Voltaren', category: 'Pain Relief', dosage: '50 mg 3 times daily', price: 11.00, indications: ['Arthritis', 'Pain', 'Inflammation', 'Migraine'], sideEffects: ['Stomach upset', 'Nausea', 'Dizziness'], image: '💊', rating: 4.3 },
  { id: 4, name: 'Aspirin', brand: 'Disprin', category: 'Pain Relief', dosage: '300-600 mg every 4-6 hours', price: 3.50, indications: ['Pain relief', 'Fever', 'Blood thinner', 'Heart attack prevention'], sideEffects: ['Stomach bleeding', 'Nausea', 'Ringing in ears'], image: '💊', rating: 4.2 },
  { id: 5, name: 'Tramadol', brand: 'Ultram', category: 'Pain Relief', dosage: '50-100 mg every 4-6 hours', price: 15.00, indications: ['Moderate to severe pain', 'Chronic pain'], sideEffects: ['Nausea', 'Dizziness', 'Constipation', 'Drowsiness'], image: '💊', rating: 4.0 },
  { id: 6, name: 'Gabapentin', brand: 'Neurontin', category: 'Pain Relief', dosage: '300-600 mg 3 times daily', price: 30.00, indications: ['Neuropathic pain', 'Seizures', 'Restless leg syndrome'], sideEffects: ['Dizziness', 'Drowsiness', 'Swelling'], image: '💊', rating: 4.1 },
  { id: 7, name: 'Pregabalin', brand: 'Lyrica', category: 'Pain Relief', dosage: '75-150 mg twice daily', price: 45.00, indications: ['Neuropathic pain', 'Fibromyalgia', 'Seizures', 'Anxiety'], sideEffects: ['Dizziness', 'Drowsiness', 'Weight gain'], image: '��', rating: 4.2 },
  { id: 8, name: 'Celecoxib', brand: 'Celebrex', category: 'Pain Relief', dosage: '100-200 mg once daily', price: 25.00, indications: ['Arthritis', 'Pain', 'Inflammation', 'Ankylosing spondylitis'], sideEffects: ['Stomach upset', 'Dizziness', 'Headache'], image: '💊', rating: 4.0 },
  { id: 9, name: 'Morphine', brand: 'MS Contin', category: 'Pain Relief', dosage: '10-30 mg every 4 hours', price: 60.00, indications: ['Severe pain', 'Cancer pain', 'Post-surgical pain'], sideEffects: ['Constipation', 'Drowsiness', 'Nausea', 'Addiction'], image: '💊', rating: 4.5 },
  { id: 10, name: 'Codeine', brand: 'Codeine Phosphate', category: 'Pain Relief', dosage: '15-60 mg every 6 hours', price: 20.00, indications: ['Mild to moderate pain', 'Cough', 'Diarrhea'], sideEffects: ['Constipation', 'Drowsiness', 'Nausea'], image: '💊', rating: 4.0 },
  { id: 11, name: 'Fentanyl', brand: 'Duragesic', category: 'Pain Relief', dosage: '25-100 mcg/hr patch', price: 80.00, indications: ['Chronic severe pain', 'Cancer pain', 'Breakthrough pain'], sideEffects: ['Constipation', 'Drowsiness', 'Nausea', 'Respiratory depression'], image: '💊', rating: 4.5 },
  { id: 12, name: 'Oxycodone', brand: 'OxyContin', category: 'Pain Relief', dosage: '5-40 mg every 4-6 hours', price: 55.00, indications: ['Severe pain', 'Chronic pain', 'Cancer pain'], sideEffects: ['Constipation', 'Drowsiness', 'Nausea', 'Addiction'], image: '💊', rating: 4.3 },
  { id: 13, name: 'Hydromorphone', brand: 'Dilaudid', category: 'Pain Relief', dosage: '2-4 mg every 4-6 hours', price: 70.00, indications: ['Severe pain', 'Cancer pain', 'Post-surgical pain'], sideEffects: ['Constipation', 'Drowsiness', 'Nausea', 'Respiratory depression'], image: '💊', rating: 4.4 },
  { id: 14, name: 'Tapentadol', brand: 'Nucynta', category: 'Pain Relief', dosage: '50-100 mg every 4-6 hours', price: 48.00, indications: ['Moderate to severe pain', 'Neuropathic pain'], sideEffects: ['Nausea', 'Dizziness', 'Constipation', 'Drowsiness'], image: '💊', rating: 4.1 },
  { id: 15, name: 'Ketorolac', brand: 'Toradol', category: 'Pain Relief', dosage: '10 mg every 4-6 hours', price: 18.00, indications: ['Moderate pain', 'Post-surgical pain', 'Migraine'], sideEffects: ['Stomach upset', 'Dizziness', 'Rash'], image: '💊', rating: 4.0 },
  { id: 16, name: 'Naproxen', brand: 'Aleve', category: 'Pain Relief', dosage: '220-440 mg twice daily', price: 9.00, indications: ['Arthritis', 'Pain', 'Inflammation', 'Gout'], sideEffects: ['Stomach upset', 'Heartburn', 'Nausea'], image: '💊', rating: 4.4 },
  { id: 17, name: 'Meloxicam', brand: 'Mobic', category: 'Pain Relief', dosage: '7.5-15 mg once daily', price: 12.00, indications: ['Arthritis', 'Pain', 'Inflammation'], sideEffects: ['Stomach upset', 'Dizziness', 'Headache'], image: '💊', rating: 4.2 },
  { id: 18, name: 'Indomethacin', brand: 'Indocin', category: 'Pain Relief', dosage: '25-50 mg 3 times daily', price: 14.00, indications: ['Arthritis', 'Gout', 'Pain', 'Inflammation'], sideEffects: ['Stomach upset', 'Headache', 'Dizziness'], image: '💊', rating: 3.8 },
  { id: 19, name: 'Nabumetone', brand: 'Relafen', category: 'Pain Relief', dosage: '500-1000 mg once daily', price: 16.00, indications: ['Arthritis', 'Pain', 'Inflammation'], sideEffects: ['Stomach upset', 'Diarrhea', 'Rash'], image: '💊', rating: 4.0 },
  { id: 20, name: 'Sulindac', brand: 'Clinoril', category: 'Pain Relief', dosage: '150-200 mg twice daily', price: 15.00, indications: ['Arthritis', 'Pain', 'Inflammation'], sideEffects: ['Stomach upset', 'Dizziness', 'Headache'], image: '💊', rating: 3.9 },
  { id: 21, name: 'Etodolac', brand: 'Lodine', category: 'Pain Relief', dosage: '400-600 mg daily', price: 17.00, indications: ['Arthritis', 'Pain', 'Inflammation'], sideEffects: ['Stomach upset', 'Dizziness', 'Headache'], image: '💊', rating: 4.0 },
  { id: 22, name: 'Flurbiprofen', brand: 'Ansaid', category: 'Pain Relief', dosage: '50-100 mg daily', price: 16.00, indications: ['Arthritis', 'Pain', 'Inflammation'], sideEffects: ['Stomach upset', 'Dizziness', 'Headache'], image: '💊', rating: 4.0 },
  { id: 23, name: 'Ketoprofen', brand: 'Orudis', category: 'Pain Relief', dosage: '50-75 mg 3 times daily', price: 13.00, indications: ['Arthritis', 'Pain', 'Inflammation'], sideEffects: ['Stomach upset', 'Dizziness', 'Headache'], image: '💊', rating: 4.0 },
  { id: 24, name: 'Oxaprozin', brand: 'Daypro', category: 'Pain Relief', dosage: '600-1200 mg daily', price: 18.00, indications: ['Arthritis', 'Pain', 'Inflammation'], sideEffects: ['Stomach upset', 'Dizziness', 'Headache'], image: '��', rating: 4.0 },
  { id: 25, name: 'Mefenamic Acid', brand: 'Ponstel', category: 'Pain Relief', dosage: '250-500 mg 3 times daily', price: 14.00, indications: ['Menstrual pain', 'Pain', 'Inflammation'], sideEffects: ['Stomach upset', 'Dizziness', 'Headache'], image: '💊', rating: 3.9 },

  // ============================================
  // ANTIBIOTICS (35 drugs)
  // ============================================
  { id: 26, name: 'Amoxicillin', brand: 'Mox, Amoxil', category: 'Antibiotics', dosage: '250-500 mg every 8 hours', price: 12.00, indications: ['Respiratory infections', 'UTI', 'Skin infections', 'Ear infections'], sideEffects: ['Nausea', 'Diarrhea', 'Rash'], image: '💊', rating: 4.6 },
  { id: 27, name: 'Azithromycin', brand: 'Zithromax', category: 'Antibiotics', dosage: '500mg day 1, 250mg days 2-5', price: 18.00, indications: ['Respiratory infections', 'STI', 'Skin infections', 'Sinusitis'], sideEffects: ['Nausea', 'Diarrhea', 'Abdominal pain'], image: '💊', rating: 4.5 },
  { id: 28, name: 'Doxycycline', brand: 'Vibramycin', category: 'Antibiotics', dosage: '100mg every 12 hours day 1, then 100mg daily', price: 17.00, indications: ['Acne', 'Malaria prevention', 'Chlamydia', 'Lyme disease'], sideEffects: ['Nausea', 'Diarrhea', 'Photosensitivity'], image: '💊', rating: 4.3 },
  { id: 29, name: 'Ciprofloxacin', brand: 'Ciprobay', category: 'Antibiotics', dosage: '500 mg twice daily', price: 22.00, indications: ['UTI', 'Respiratory infections', 'GI infections', 'Bone infections'], sideEffects: ['Nausea', 'Diarrhea', 'Tendon rupture'], image: '💊', rating: 4.2 },
  { id: 30, name: 'Clarithromycin', brand: 'Klacid', category: 'Antibiotics', dosage: '250-500 mg twice daily', price: 28.00, indications: ['Respiratory infections', 'H. pylori', 'Skin infections', 'Pneumonia'], sideEffects: ['Nausea', 'Diarrhea', 'Taste disturbance'], image: '💊', rating: 4.1 },
  { id: 31, name: 'Amikacin', brand: 'Amikin', category: 'Antibiotics', dosage: '15-20 mg/kg daily', price: 55.00, indications: ['Severe infections', 'Gram-negative bacteria', 'Septicemia'], sideEffects: ['Nephrotoxicity', 'Ototoxicity', 'Neurotoxicity'], image: '💊', rating: 4.4 },
  { id: 32, name: 'Gentamicin', brand: 'Garamycin', category: 'Antibiotics', dosage: '3-5 mg/kg daily', price: 35.00, indications: ['Severe infections', 'UTI', 'Septicemia', 'Pneumonia'], sideEffects: ['Nephrotoxicity', 'Ototoxicity', 'Nausea'], image: '💊', rating: 4.0 },
  { id: 33, name: 'Tobramycin', brand: 'Tobi', category: 'Antibiotics', dosage: '3-5 mg/kg daily', price: 40.00, indications: ['Severe infections', 'Cystic fibrosis', 'Pneumonia'], sideEffects: ['Nephrotoxicity', 'Ototoxicity', 'Nausea'], image: '💊', rating: 4.1 },
  { id: 34, name: 'Vancomycin', brand: 'Vancocin', category: 'Antibiotics', dosage: '500 mg every 6 hours', price: 65.00, indications: ['MRSA', 'Severe infections', 'C. difficile', 'Endocarditis'], sideEffects: ['Nephrotoxicity', 'Ototoxicity', 'Rash'], image: '💊', rating: 4.6 },
  { id: 35, name: 'Metronidazole', brand: 'Flagyl', category: 'Antibiotics', dosage: '500 mg 3 times daily', price: 14.00, indications: ['Bacterial vaginosis', 'H. pylori', 'GI infections', 'Rosacea'], sideEffects: ['Nausea', 'Diarrhea', 'Metallic taste'], image: '💊', rating: 4.2 },
  { id: 36, name: 'Erythromycin', brand: 'Erythrocin', category: 'Antibiotics', dosage: '250-500 mg every 6 hours', price: 16.00, indications: ['Respiratory infections', 'Skin infections', 'Bacterial infections'], sideEffects: ['Nausea', 'Diarrhea', 'Abdominal pain'], image: '💊', rating: 3.8 },
  { id: 37, name: 'Penicillin', brand: 'Pen-Vee K', category: 'Antibiotics', dosage: '250-500 mg every 6 hours', price: 10.00, indications: ['Bacterial infections', 'Strep throat', 'Pneumonia', 'Syphilis'], sideEffects: ['Allergic reaction', 'Diarrhea', 'Nausea'], image: '💊', rating: 4.5 },
  { id: 38, name: 'Cephalexin', brand: 'Keflex', category: 'Antibiotics', dosage: '250-500 mg every 6 hours', price: 13.00, indications: ['Skin infections', 'Respiratory infections', 'UTI', 'Ear infections'], sideEffects: ['Diarrhea', 'Nausea', 'Rash'], image: '💊', rating: 4.3 },
  { id: 39, name: 'Cefuroxime', brand: 'Zinacef', category: 'Antibiotics', dosage: '250-500 mg twice daily', price: 24.00, indications: ['Respiratory infections', 'UTI', 'Skin infections', 'Lyme disease'], sideEffects: ['Diarrhea', 'Nausea', 'Rash'], image: '💊', rating: 4.1 },
  { id: 40, name: 'Ceftriaxone', brand: 'Rocephin', category: 'Antibiotics', dosage: '1-2 g daily', price: 50.00, indications: ['Severe infections', 'Meningitis', 'Gonorrhea', 'Pneumonia'], sideEffects: ['Diarrhea', 'Rash', 'Nausea'], image: '💊', rating: 4.6 },
  { id: 41, name: 'Ampicillin', brand: 'Principen', category: 'Antibiotics', dosage: '250-500 mg every 6 hours', price: 11.00, indications: ['Respiratory infections', 'UTI', 'Meningitis', 'Bacterial infections'], sideEffects: ['Diarrhea', 'Rash', 'Nausea'], image: '💊', rating: 4.0 },
  { id: 42, name: 'Clindamycin', brand: 'Cleocin', category: 'Antibiotics', dosage: '150-300 mg every 6 hours', price: 22.00, indications: ['Skin infections', 'Respiratory infections', 'Bacterial vaginosis', 'Toxoplasmosis'], sideEffects: ['Diarrhea', 'Nausea', 'Abdominal pain'], image: '💊', rating: 4.2 },
  { id: 43, name: 'Nitrofurantoin', brand: 'Macrobid', category: 'Antibiotics', dosage: '100 mg twice daily', price: 15.00, indications: ['UTI', 'Cystitis', 'Pyelonephritis'], sideEffects: ['Nausea', 'Headache', 'Dizziness'], image: '💊', rating: 4.4 },
  { id: 44, name: 'Trimethoprim-Sulfamethoxazole', brand: 'Bactrim', category: 'Antibiotics', dosage: '800/160 mg twice daily', price: 18.00, indications: ['UTI', 'Respiratory infections', 'MRSA', 'PCP pneumonia'], sideEffects: ['Nausea', 'Rash', 'Sun sensitivity'], image: '💊', rating: 4.1 },
  { id: 45, name: 'Levofloxacin', brand: 'Levaquin', category: 'Antibiotics', dosage: '500 mg once daily', price: 28.00, indications: ['Respiratory infections', 'UTI', 'Sinusitis', 'Prostatitis'], sideEffects: ['Nausea', 'Diarrhea', 'Tendon rupture'], image: '💊', rating: 3.9 },
  { id: 46, name: 'Moxifloxacin', brand: 'Avelox', category: 'Antibiotics', dosage: '400 mg once daily', price: 32.00, indications: ['Respiratory infections', 'Sinusitis', 'Skin infections'], sideEffects: ['Nausea', 'Diarrhea', 'Tendon rupture'], image: '💊', rating: 4.0 },
  { id: 47, name: 'Daptomycin', brand: 'Cubicin', category: 'Antibiotics', dosage: '4-6 mg/kg daily', price: 95.00, indications: ['MRSA', 'Complicated skin infections', 'Bacteremia'], sideEffects: ['Muscle pain', 'Nausea', 'Diarrhea'], image: '💊', rating: 4.5 },
  { id: 48, name: 'Linezolid', brand: 'Zyvox', category: 'Antibiotics', dosage: '600 mg twice daily', price: 85.00, indications: ['MRSA', 'VRE', 'Pneumonia', 'Complicated skin infections'], sideEffects: ['Nausea', 'Headache', 'Thrombocytopenia'], image: '💊', rating: 4.4 },
  { id: 49, name: 'Tigecycline', brand: 'Tygacil', category: 'Antibiotics', dosage: '100 mg initial, 50 mg every 12 hours', price: 90.00, indications: ['Complicated skin infections', 'Intra-abdominal infections', 'Community-acquired pneumonia'], sideEffects: ['Nausea', 'Diarrhea', 'Vomiting'], image: '💊', rating: 4.2 },
  { id: 50, name: 'Cefdinir', brand: 'Omnicef', category: 'Antibiotics', dosage: '300 mg twice daily', price: 20.00, indications: ['Respiratory infections', 'Skin infections', 'Ear infections', 'UTI'], sideEffects: ['Diarrhea', 'Nausea', 'Headache'], image: '💊', rating: 4.1 },
  { id: 51, name: 'Cefpodoxime', brand: 'Vantin', category: 'Antibiotics', dosage: '200 mg twice daily', price: 22.00, indications: ['Respiratory infections', 'Skin infections', 'UTI'], sideEffects: ['Diarrhea', 'Nausea', 'Rash'], image: '💊', rating: 4.0 },
  { id: 52, name: 'Ertapenem', brand: 'Invanz', category: 'Antibiotics', dosage: '1 g once daily', price: 75.00, indications: ['Complicated skin infections', 'Intra-abdominal infections', 'UTI', 'Pneumonia'], sideEffects: ['Diarrhea', 'Nausea', 'Headache'], image: '💊', rating: 4.3 },
  { id: 53, name: 'Imipenem-Cilastatin', brand: 'Primaxin', category: 'Antibiotics', dosage: '250-500 mg every 6 hours', price: 80.00, indications: ['Severe infections', 'Septicemia', 'Complicated infections'], sideEffects: ['Diarrhea', 'Nausea', 'Seizures'], image: '💊', rating: 4.4 },
  { id: 54, name: 'Meropenem', brand: 'Merrem', category: 'Antibiotics', dosage: '500 mg every 8 hours', price: 85.00, indications: ['Severe infections', 'Meningitis', 'Septicemia', 'Complicated infections'], sideEffects: ['Diarrhea', 'Nausea', 'Headache'], image: '💊', rating: 4.5 },
  { id: 55, name: 'Piperacillin-Tazobactam', brand: 'Zosyn', category: 'Antibiotics', dosage: '4.5 g every 6 hours', price: 70.00, indications: ['Severe infections', 'Pneumonia', 'Septicemia', 'Complicated infections'], sideEffects: ['Diarrhea', 'Nausea', 'Rash'], image: '💊', rating: 4.4 },
  { id: 56, name: 'Cefazolin', brand: 'Ancef', category: 'Antibiotics', dosage: '1 g every 8 hours', price: 25.00, indications: ['Surgical prophylaxis', 'Skin infections', 'Pneumonia'], sideEffects: ['Diarrhea', 'Nausea', 'Rash'], image: '💊', rating: 4.2 },
  { id: 57, name: 'Cefotaxime', brand: 'Claforan', category: 'Antibiotics', dosage: '1-2 g every 6-8 hours', price: 45.00, indications: ['Severe infections', 'Meningitis', 'Pneumonia'], sideEffects: ['Diarrhea', 'Nausea', 'Rash'], image: '💊', rating: 4.3 },
  { id: 58, name: 'Ceftazidime', brand: 'Fortaz', category: 'Antibiotics', dosage: '1-2 g every 8 hours', price: 48.00, indications: ['Severe infections', 'Pseudomonas', 'Pneumonia'], sideEffects: ['Diarrhea', 'Nausea', 'Rash'], image: '💊', rating: 4.3 },
  { id: 59, name: 'Ceftriaxone', brand: 'Rocephin', category: 'Antibiotics', dosage: '1-2 g daily', price: 50.00, indications: ['Severe infections', 'Meningitis', 'Gonorrhea'], sideEffects: ['Diarrhea', 'Rash', 'Nausea'], image: '💊', rating: 4.6 },
  { id: 60, name: 'Cefixime', brand: 'Suprax', category: 'Antibiotics', dosage: '400 mg once daily', price: 23.00, indications: ['UTI', 'Pharyngitis', 'Gonorrhea'], sideEffects: ['Diarrhea', 'Nausea', 'Rash'], image: '��', rating: 4.1 },

  // ============================================
  // CARDIOVASCULAR (30 drugs)
  // ============================================
  { id: 61, name: 'Amlodipine', brand: 'Norvasc', category: 'Cardiovascular', dosage: '5-10 mg once daily', price: 10.00, indications: ['Hypertension', 'Angina', 'Coronary artery disease'], sideEffects: ['Swelling', 'Headache', 'Dizziness'], image: '❤️', rating: 4.5 },
  { id: 62, name: 'Atorvastatin', brand: 'Lipitor', category: 'Cardiovascular', dosage: '10-40 mg once daily', price: 15.00, indications: ['Hyperlipidemia', 'Heart disease prevention', 'Strokes prevention'], sideEffects: ['Muscle pain', 'Joint pain', 'Nausea'], image: '❤️', rating: 4.6 },
  { id: 63, name: 'Losartan', brand: 'Cozaar', category: 'Cardiovascular', dosage: '25-100 mg once daily', price: 14.00, indications: ['Hypertension', 'Diabetic nephropathy', 'Stroke prevention'], sideEffects: ['Dizziness', 'Headache', 'Fatigue'], image: '❤️', rating: 4.4 },
  { id: 64, name: 'Propranolol', brand: 'Inderal', category: 'Cardiovascular', dosage: '40-160 mg twice daily', price: 12.00, indications: ['Hypertension', 'Angina', 'Migraine prevention', 'Anxiety'], sideEffects: ['Fatigue', 'Cold extremities', 'Dizziness'], image: '❤️', rating: 4.3 },
  { id: 65, name: 'Furosemide', brand: 'Lasix', category: 'Cardiovascular', dosage: '20-80 mg daily', price: 9.00, indications: ['Heart failure', 'Edema', 'Hypertension', 'Liver cirrhosis'], sideEffects: ['Dehydration', 'Electrolyte imbalance', 'Dizziness'], image: '❤️', rating: 4.2 },
  { id: 66, name: 'Hydrochlorothiazide', brand: 'HCTZ', category: 'Cardiovascular', dosage: '12.5-25 mg once daily', price: 8.00, indications: ['Hypertension', 'Edema', 'Kidney stones'], sideEffects: ['Dehydration', 'Electrolyte imbalance', 'Dizziness'], image: '❤️', rating: 4.0 },
  { id: 67, name: 'Lisinopril', brand: 'Prinivil', category: 'Cardiovascular', dosage: '10-40 mg once daily', price: 11.00, indications: ['Hypertension', 'Heart failure', 'Heart attack prevention'], sideEffects: ['Cough', 'Dizziness', 'Headache'], image: '❤️', rating: 4.5 },
  { id: 68, name: 'Enalapril', brand: 'Vasotec', category: 'Cardiovascular', dosage: '5-40 mg once daily', price: 13.00, indications: ['Hypertension', 'Heart failure', 'Kidney disease'], sideEffects: ['Cough', 'Dizziness', 'Headache'], image: '❤️', rating: 4.3 },
  { id: 69, name: 'Ramipril', brand: 'Altace', category: 'Cardiovascular', dosage: '2.5-20 mg once daily', price: 14.00, indications: ['Hypertension', 'Heart failure', 'Heart attack prevention'], sideEffects: ['Cough', 'Dizziness', 'Headache'], image: '❤️', rating: 4.4 },
  { id: 70, name: 'Valsartan', brand: 'Diovan', category: 'Cardiovascular', dosage: '80-320 mg once daily', price: 16.00, indications: ['Hypertension', 'Heart failure', 'Heart attack prevention'], sideEffects: ['Dizziness', 'Fatigue', 'Headache'], image: '❤️', rating: 4.4 },
  { id: 71, name: 'Candesartan', brand: 'Atacand', category: 'Cardiovascular', dosage: '8-32 mg once daily', price: 15.00, indications: ['Hypertension', 'Heart failure'], sideEffects: ['Dizziness', 'Fatigue', 'Headache'], image: '❤️', rating: 4.2 },
  { id: 72, name: 'Irbesartan', brand: 'Avapro', category: 'Cardiovascular', dosage: '150-300 mg once daily', price: 16.00, indications: ['Hypertension', 'Diabetic nephropathy'], sideEffects: ['Dizziness', 'Fatigue', 'Headache'], image: '❤️', rating: 4.3 },
  { id: 73, name: 'Telmisartan', brand: 'Micardis', category: 'Cardiovascular', dosage: '40-80 mg once daily', price: 17.00, indications: ['Hypertension', 'Cardiovascular prevention'], sideEffects: ['Dizziness', 'Headache', 'Back pain'], image: '❤️', rating: 4.4 },
  { id: 74, name: 'Olmesartan', brand: 'Benicar', category: 'Cardiovascular', dosage: '20-40 mg once daily', price: 16.00, indications: ['Hypertension'], sideEffects: ['Dizziness', 'Headache', 'Diarrhea'], image: '❤️', rating: 4.1 },
  { id: 75, name: 'Ezetimibe', brand: 'Zetia', category: 'Cardiovascular', dosage: '10 mg once daily', price: 25.00, indications: ['Hyperlipidemia', 'Cholesterol lowering'], sideEffects: ['Diarrhea', 'Joint pain', 'Headache'], image: '❤️', rating: 4.0 },
  { id: 76, name: 'Fenofibrate', brand: 'Tricor', category: 'Cardiovascular', dosage: '145 mg once daily', price: 22.00, indications: ['Hyperlipidemia', 'Triglyceride lowering'], sideEffects: ['Nausea', 'Headache', 'Muscle pain'], image: '❤️', rating: 3.9 },
  { id: 77, name: 'Gemfibrozil', brand: 'Lopid', category: 'Cardiovascular', dosage: '600 mg twice daily', price: 20.00, indications: ['Hyperlipidemia', 'Triglyceride lowering'], sideEffects: ['Nausea', 'Headache', 'Muscle pain'], image: '❤️', rating: 3.8 },
  { id: 78, name: 'Niacin', brand: 'Niaspan', category: 'Cardiovascular', dosage: '500-2000 mg daily', price: 18.00, indications: ['Hyperlipidemia', 'Cholesterol lowering'], sideEffects: ['Flushing', 'Headache', 'Nausea'], image: '❤️', rating: 3.7 },
  { id: 79, name: 'Clopidogrel', brand: 'Plavix', category: 'Cardiovascular', dosage: '75 mg once daily', price: 30.00, indications: ['Heart attack prevention', 'Stroke prevention', 'CAD'], sideEffects: ['Bleeding', 'Bruising', 'Nausea'], image: '❤️', rating: 4.5 },
  { id: 80, name: 'Aspirin', brand: 'Bayer', category: 'Cardiovascular', dosage: '81-325 mg once daily', price: 5.00, indications: ['Heart attack prevention', 'Stroke prevention', 'Pain relief'], sideEffects: ['Bleeding', 'Stomach upset', 'Bruising'], image: '❤️', rating: 4.6 },
  { id: 81, name: 'Warfarin', brand: 'Coumadin', category: 'Cardiovascular', dosage: '2-10 mg once daily', price: 22.00, indications: ['Blood clots', 'Atrial fibrillation', 'DVT', 'PE'], sideEffects: ['Bleeding', 'Bruising', 'Nausea'], image: '❤️', rating: 4.2 },
  { id: 82, name: 'Apixaban', brand: 'Eliquis', category: 'Cardiovascular', dosage: '5 mg twice daily', price: 45.00, indications: ['Blood clots', 'Atrial fibrillation', 'DVT', 'PE'], sideEffects: ['Bleeding', 'Bruising', 'Nausea'], image: '❤️', rating: 4.6 },
  { id: 83, name: 'Rivaroxaban', brand: 'Xarelto', category: 'Cardiovascular', dosage: '15-20 mg once daily', price: 48.00, indications: ['Blood clots', 'Atrial fibrillation', 'DVT', 'PE'], sideEffects: ['Bleeding', 'Bruising', 'Nausea'], image: '❤️', rating: 4.5 },
  { id: 84, name: 'Dabigatran', brand: 'Pradaxa', category: 'Cardiovascular', dosage: '150 mg twice daily', price: 50.00, indications: ['Blood clots', 'Atrial fibrillation', 'DVT', 'PE'], sideEffects: ['Bleeding', 'Bruising', 'Nausea'], image: '❤️', rating: 4.4 },
  { id: 85, name: 'Spironolactone', brand: 'Aldactone', category: 'Cardiovascular', dosage: '25-100 mg once daily', price: 15.00, indications: ['Heart failure', 'Edema', 'Hypertension', 'Ascites'], sideEffects: ['Hyperkalemia', 'Dizziness', 'Nausea'], image: '❤️', rating: 4.3 },
  { id: 86, name: 'Carvedilol', brand: 'Coreg', category: 'Cardiovascular', dosage: '6.25-25 mg twice daily', price: 18.00, indications: ['Heart failure', 'Hypertension', 'Left ventricular dysfunction'], sideEffects: ['Dizziness', 'Fatigue', 'Bradycardia'], image: '❤️', rating: 4.4 },
  { id: 87, name: 'Metoprolol', brand: 'Lopressor', category: 'Cardiovascular', dosage: '50-100 mg twice daily', price: 12.00, indications: ['Hypertension', 'Angina', 'Heart failure', 'Migraine prevention'], sideEffects: ['Fatigue', 'Dizziness', 'Bradycardia'], image: '❤️', rating: 4.3 },
  { id: 88, name: 'Bisoprolol', brand: 'Zebeta', category: 'Cardiovascular', dosage: '2.5-10 mg once daily', price: 14.00, indications: ['Hypertension', 'Heart failure', 'Angina'], sideEffects: ['Fatigue', 'Dizziness', 'Bradycardia'], image: '❤️', rating: 4.3 },
  { id: 89, name: 'Atenolol', brand: 'Tenormin', category: 'Cardiovascular', dosage: '25-100 mg once daily', price: 11.00, indications: ['Hypertension', 'Angina', 'Heart attack prevention'], sideEffects: ['Fatigue', 'Cold extremities', 'Dizziness'], image: '❤️', rating: 4.2 },
  { id: 90, name: 'Nebivolol', brand: 'Bystolic', category: 'Cardiovascular', dosage: '2.5-10 mg once daily', price: 16.00, indications: ['Hypertension', 'Heart failure'], sideEffects: ['Fatigue', 'Dizziness', 'Headache'], image: '❤️', rating: 4.2 },

  // ============================================
  // DIABETES (20 drugs)
  // ============================================
  { id: 91, name: 'Metformin', brand: 'Glycomet', category: 'Diabetes', dosage: '500-1000 mg twice daily', price: 8.00, indications: ['Type 2 diabetes', 'PCOS', 'Prediabetes'], sideEffects: ['Nausea', 'Diarrhea', 'Metallic taste'], image: '🩸', rating: 4.6 },
  { id: 92, name: 'Insulin Glargine', brand: 'Lantus', category: 'Diabetes', dosage: 'Varies based on blood sugar', price: 85.00, indications: ['Type 1 diabetes', 'Type 2 diabetes'], sideEffects: ['Hypoglycemia', 'Weight gain', 'Lipodystrophy'], image: '🩸', rating: 4.5 },
  { id: 93, name: 'Insulin Aspart', brand: 'Novolog', category: 'Diabetes', dosage: 'Varies based on blood sugar', price: 90.00, indications: ['Type 1 diabetes', 'Type 2 diabetes'], sideEffects: ['Hypoglycemia', 'Weight gain', 'Lipodystrophy'], image: '🩸', rating: 4.4 },
  { id: 94, name: 'Glipizide', brand: 'Glucotrol', category: 'Diabetes', dosage: '5-10 mg daily', price: 14.00, indications: ['Type 2 diabetes'], sideEffects: ['Hypoglycemia', 'Weight gain', 'Nausea'], image: '🩸', rating: 4.1 },
  { id: 95, name: 'Glimepiride', brand: 'Amaryl', category: 'Diabetes', dosage: '1-4 mg once daily', price: 15.00, indications: ['Type 2 diabetes'], sideEffects: ['Hypoglycemia', 'Weight gain', 'Nausea'], image: '🩸', rating: 4.2 },
  { id: 96, name: 'Glyburide', brand: 'Diabeta', category: 'Diabetes', dosage: '2.5-10 mg once daily', price: 12.00, indications: ['Type 2 diabetes'], sideEffects: ['Hypoglycemia', 'Weight gain', 'Nausea'], image: '🩸', rating: 3.9 },
  { id: 97, name: 'Pioglitazone', brand: 'Actos', category: 'Diabetes', dosage: '15-45 mg once daily', price: 25.00, indications: ['Type 2 diabetes'], sideEffects: ['Weight gain', 'Edema', 'Headache'], image: '🩸', rating: 4.0 },
  { id: 98, name: 'Rosiglitazone', brand: 'Avandia', category: 'Diabetes', dosage: '2-8 mg once daily', price: 28.00, indications: ['Type 2 diabetes'], sideEffects: ['Weight gain', 'Edema', 'Headache'], image: '🩸', rating: 3.8 },
  { id: 99, name: 'Sitagliptin', brand: 'Januvia', category: 'Diabetes', dosage: '100 mg once daily', price: 35.00, indications: ['Type 2 diabetes'], sideEffects: ['Headache', 'GI symptoms', 'Joint pain'], image: '🩸', rating: 4.3 },
  { id: 100, name: 'Saxagliptin', brand: 'Onglyza', category: 'Diabetes', dosage: '2.5-5 mg once daily', price: 32.00, indications: ['Type 2 diabetes'], sideEffects: ['Headache', 'GI symptoms', 'Joint pain'], image: '🩸', rating: 4.1 },
  { id: 101, name: 'Linagliptin', brand: 'Tradjenta', category: 'Diabetes', dosage: '5 mg once daily', price: 33.00, indications: ['Type 2 diabetes'], sideEffects: ['Headache', 'GI symptoms', 'Joint pain'], image: '🩸', rating: 4.2 },
  { id: 102, name: 'Empagliflozin', brand: 'Jardiance', category: 'Diabetes', dosage: '10-25 mg once daily', price: 40.00, indications: ['Type 2 diabetes', 'Heart failure prevention'], sideEffects: ['UTI', 'Dehydration', 'Hypoglycemia'], image: '🩸', rating: 4.5 },
  { id: 103, name: 'Dapagliflozin', brand: 'Farxiga', category: 'Diabetes', dosage: '5-10 mg once daily', price: 42.00, indications: ['Type 2 diabetes', 'Heart failure prevention', 'Kidney disease'], sideEffects: ['UTI', 'Dehydration', 'Hypoglycemia'], image: '🩸', rating: 4.4 },
  { id: 104, name: 'Canagliflozin', brand: 'Invokana', category: 'Diabetes', dosage: '100-300 mg once daily', price: 38.00, indications: ['Type 2 diabetes'], sideEffects: ['UTI', 'Dehydration', 'Hypoglycemia'], image: '🩸', rating: 4.0 },
  { id: 105, name: 'Exenatide', brand: 'Byetta', category: 'Diabetes', dosage: '5-10 mcg twice daily', price: 55.00, indications: ['Type 2 diabetes'], sideEffects: ['Nausea', 'Vomiting', 'Diarrhea'], image: '🩸', rating: 4.2 },
  { id: 106, name: 'Liraglutide', brand: 'Victoza', category: 'Diabetes', dosage: '0.6-1.8 mg daily', price: 60.00, indications: ['Type 2 diabetes', 'Weight management'], sideEffects: ['Nausea', 'Vomiting', 'Diarrhea'], image: '🩸', rating: 4.4 },
  { id: 107, name: 'Semaglutide', brand: 'Ozempic', category: 'Diabetes', dosage: '0.5-1 mg weekly', price: 65.00, indications: ['Type 2 diabetes', 'Weight management'], sideEffects: ['Nausea', 'Vomiting', 'Diarrhea'], image: '🩸', rating: 4.6 },
  { id: 108, name: 'Dulaglutide', brand: 'Trulicity', category: 'Diabetes', dosage: '0.75-1.5 mg weekly', price: 62.00, indications: ['Type 2 diabetes'], sideEffects: ['Nausea', 'Vomiting', 'Diarrhea'], image: '🩸', rating: 4.4 },
  { id: 109, name: 'Acarbose', brand: 'Precose', category: 'Diabetes', dosage: '25-100 mg 3 times daily', price: 20.00, indications: ['Type 2 diabetes'], sideEffects: ['Flatulence', 'Diarrhea', 'Abdominal pain'], image: '🩸', rating: 3.8 },
  { id: 110, name: 'Repaglinide', brand: 'Prandin', category: 'Diabetes', dosage: '0.5-4 mg before meals', price: 22.00, indications: ['Type 2 diabetes'], sideEffects: ['Hypoglycemia', 'Weight gain', 'Nausea'], image: '🩸', rating: 4.0 },

  // ============================================
  // RESPIRATORY (20 drugs)
  // ============================================
  { id: 111, name: 'Albuterol', brand: 'Ventolin', category: 'Respiratory', dosage: '2 puffs every 4-6 hours', price: 65.00, indications: ['Asthma', 'COPD', 'Bronchospasm'], sideEffects: ['Tremor', 'Headache', 'Palpitations'], image: '🫁', rating: 4.5 },
  { id: 112, name: 'Montelukast', brand: 'Singulair', category: 'Respiratory', dosage: '10 mg once daily', price: 22.00, indications: ['Asthma', 'Allergic rhinitis', 'Bronchospasm'], sideEffects: ['Headache', 'Stomach pain', 'Insomnia'], image: '🫁', rating: 4.2 },
  { id: 113, name: 'Theophylline', brand: 'Theo-24', category: 'Respiratory', dosage: '200-400 mg daily', price: 35.00, indications: ['Asthma', 'COPD', 'Bronchospasm'], sideEffects: ['Nausea', 'Tremor', 'Palpitations'], image: '🫁', rating: 3.8 },
  { id: 114, name: 'Budesonide', brand: 'Pulmicort', category: 'Respiratory', dosage: '1-2 puffs twice daily', price: 70.00, indications: ['Asthma', 'COPD'], sideEffects: ['Sore throat', 'Cough', 'Headache'], image: '🫁', rating: 4.3 },
  { id: 115, name: 'Fluticasone', brand: 'Flovent', category: 'Respiratory', dosage: '2 puffs twice daily', price: 75.00, indications: ['Asthma', 'COPD'], sideEffects: ['Sore throat', 'Cough', 'Headache'], image: '🫁', rating: 4.4 },
  { id: 116, name: 'Salmeterol', brand: 'Serevent', category: 'Respiratory', dosage: '2 puffs twice daily', price: 80.00, indications: ['Asthma', 'COPD'], sideEffects: ['Tremor', 'Headache', 'Palpitations'], image: '🫁', rating: 4.1 },
  { id: 117, name: 'Formoterol', brand: 'Foradil', category: 'Respiratory', dosage: '1 puff twice daily', price: 78.00, indications: ['Asthma', 'COPD'], sideEffects: ['Tremor', 'Headache', 'Palpitations'], image: '🫁', rating: 4.2 },
  { id: 118, name: 'Tiotropium', brand: 'Spiriva', category: 'Respiratory', dosage: '1 puff once daily', price: 90.00, indications: ['COPD', 'Asthma'], sideEffects: ['Dry mouth', 'Sore throat', 'Headache'], image: '🫁', rating: 4.4 },
  { id: 119, name: 'Ipratropium', brand: 'Atrovent', category: 'Respiratory', dosage: '1-2 puffs every 4-6 hours', price: 55.00, indications: ['COPD', 'Asthma'], sideEffects: ['Dry mouth', 'Cough', 'Headache'], image: '🫁', rating: 4.0 },
  { id: 120, name: 'Levalbuterol', brand: 'Xopenex', category: 'Respiratory', dosage: '1-2 puffs every 4-6 hours', price: 68.00, indications: ['Asthma', 'COPD', 'Bronchospasm'], sideEffects: ['Tremor', 'Headache', 'Palpitations'], image: '🫁', rating: 4.2 },
  { id: 121, name: 'Flunisolide', brand: 'Aerospan', category: 'Respiratory', dosage: '2 puffs twice daily', price: 72.00, indications: ['Asthma'], sideEffects: ['Sore throat', 'Cough', 'Headache'], image: '🫁', rating: 4.0 },
  { id: 122, name: 'Mometasone', brand: 'Asmanex', category: 'Respiratory', dosage: '2 puffs twice daily', price: 74.00, indications: ['Asthma'], sideEffects: ['Sore throat', 'Cough', 'Headache'], image: '🫁', rating: 4.3 },
  { id: 123, name: 'Ciclesonide', brand: 'Alvesco', category: 'Respiratory', dosage: '2 puffs twice daily', price: 76.00, indications: ['Asthma'], sideEffects: ['Sore throat', 'Cough', 'Headache'], image: '🫁', rating: 4.2 },
  { id: 124, name: 'Zafirlukast', brand: 'Accolate', category: 'Respiratory', dosage: '20 mg twice daily', price: 45.00, indications: ['Asthma'], sideEffects: ['Headache', 'Nausea', 'Dizziness'], image: '🫁', rating: 3.9 },
  { id: 125, name: 'Zileuton', brand: 'Zyflo', category: 'Respiratory', dosage: '600 mg 4 times daily', price: 48.00, indications: ['Asthma'], sideEffects: ['Headache', 'Nausea', 'Liver enzyme elevation'], image: '🫁', rating: 3.7 },
  { id: 126, name: 'Beclomethasone', brand: 'Qvar', category: 'Respiratory', dosage: '1-2 puffs twice daily', price: 70.00, indications: ['Asthma'], sideEffects: ['Sore throat', 'Cough', 'Headache'], image: '🫁', rating: 4.2 },
  { id: 127, name: 'Fluticasone/Salmeterol', brand: 'Advair', category: 'Respiratory', dosage: '1 puff twice daily', price: 95.00, indications: ['Asthma', 'COPD'], sideEffects: ['Sore throat', 'Cough', 'Tremor'], image: '🫁', rating: 4.5 },
  { id: 128, name: 'Budesonide/Formoterol', brand: 'Symbicort', category: 'Respiratory', dosage: '1-2 puffs twice daily', price: 92.00, indications: ['Asthma', 'COPD'], sideEffects: ['Sore throat', 'Cough', 'Tremor'], image: '🫁', rating: 4.4 },
  { id: 129, name: 'Mometasone/Formoterol', brand: 'Dulera', category: 'Respiratory', dosage: '1-2 puffs twice daily', price: 90.00, indications: ['Asthma'], sideEffects: ['Sore throat', 'Cough', 'Tremor'], image: '🫁', rating: 4.3 },
  { id: 130, name: 'Flunisolide', brand: 'Aerospan', category: 'Respiratory', dosage: '2 puffs twice daily', price: 72.00, indications: ['Asthma'], sideEffects: ['Sore throat', 'Cough', 'Headache'], image: '🫁', rating: 4.0 },

  // ============================================
  // GASTROINTESTINAL (20 drugs)
  // ============================================
  { id: 131, name: 'Omeprazole', brand: 'Prilosec', category: 'Gastrointestinal', dosage: '20 mg once daily', price: 12.00, indications: ['GERD', 'Peptic ulcer', 'Heartburn', 'Dyspepsia'], sideEffects: ['Headache', 'Nausea', 'Constipation'], image: '🧪', rating: 4.5 },
  { id: 132, name: 'Pantoprazole', brand: 'Protonix', category: 'Gastrointestinal', dosage: '40 mg once daily', price: 14.00, indications: ['GERD', 'Peptic ulcer', 'Heartburn'], sideEffects: ['Headache', 'Nausea', 'Constipation'], image: '🧪', rating: 4.4 },
  { id: 133, name: 'Esomeprazole', brand: 'Nexium', category: 'Gastrointestinal', dosage: '20-40 mg once daily', price: 16.00, indications: ['GERD', 'Peptic ulcer', 'Heartburn'], sideEffects: ['Headache', 'Nausea', 'Constipation'], image: '🧪', rating: 4.3 },
  { id: 134, name: 'Lansoprazole', brand: 'Prevacid', category: 'Gastrointestinal', dosage: '15-30 mg once daily', price: 13.00, indications: ['GERD', 'Peptic ulcer', 'Heartburn'], sideEffects: ['Headache', 'Nausea', 'Constipation'], image: '🧪', rating: 4.2 },
  { id: 135, name: 'Rabeprazole', brand: 'Aciphex', category: 'Gastrointestinal', dosage: '20 mg once daily', price: 15.00, indications: ['GERD', 'Peptic ulcer', 'Heartburn'], sideEffects: ['Headache', 'Nausea', 'Constipation'], image: '🧪', rating: 4.3 },
  { id: 136, name: 'Famotidine', brand: 'Pepcid', category: 'Gastrointestinal', dosage: '20-40 mg twice daily', price: 10.00, indications: ['GERD', 'Peptic ulcer', 'Heartburn', 'Dyspepsia'], sideEffects: ['Headache', 'Constipation', 'Diarrhea'], image: '🧪', rating: 4.2 },
  { id: 137, name: 'Ranitidine', brand: 'Zantac', category: 'Gastrointestinal', dosage: '150-300 mg twice daily', price: 9.00, indications: ['GERD', 'Peptic ulcer', 'Heartburn'], sideEffects: ['Headache', 'Nausea', 'Constipation'], image: '🧪', rating: 4.0 },
  { id: 138, name: 'Cimetidine', brand: 'Tagamet', category: 'Gastrointestinal', dosage: '400-800 mg twice daily', price: 11.00, indications: ['GERD', 'Peptic ulcer', 'Heartburn'], sideEffects: ['Headache', 'Dizziness', 'Constipation'], image: '🧪', rating: 3.8 },
  { id: 139, name: 'Nizatidine', brand: 'Axid', category: 'Gastrointestinal', dosage: '150-300 mg twice daily', price: 12.00, indications: ['GERD', 'Peptic ulcer', 'Heartburn'], sideEffects: ['Headache', 'Nausea', 'Constipation'], image: '🧪', rating: 4.0 },
  { id: 140, name: 'Sucralfate', brand: 'Carafate', category: 'Gastrointestinal', dosage: '1 g 4 times daily', price: 18.00, indications: ['Peptic ulcer', 'GERD', 'Duodenal ulcer'], sideEffects: ['Constipation', 'Dry mouth', 'Nausea'], image: '🧪', rating: 4.0 },
  { id: 141, name: 'Misoprostol', brand: 'Cytotec', category: 'Gastrointestinal', dosage: '200 mcg 4 times daily', price: 22.00, indications: ['Peptic ulcer prevention', 'NSAID-induced ulcers'], sideEffects: ['Diarrhea', 'Nausea', 'Abdominal pain'], image: '🧪', rating: 3.8 },
  { id: 142, name: 'Bismuth Subsalicylate', brand: 'Pepto-Bismol', category: 'Gastrointestinal', dosage: '525 mg every 30 minutes', price: 8.00, indications: ['Diarrhea', 'Heartburn', 'Nausea', 'Indigestion'], sideEffects: ['Dark tongue', 'Black stool', 'Nausea'], image: '🧪', rating: 4.0 },
  { id: 143, name: 'Loperamide', brand: 'Imodium', category: 'Gastrointestinal', dosage: '4 mg initial, 2 mg after each loose stool', price: 7.00, indications: ['Diarrhea', 'Travelers diarrhea'], sideEffects: ['Constipation', 'Dizziness', 'Nausea'], image: '🧪', rating: 4.3 },
  { id: 144, name: 'Dicyclomine', brand: 'Bentyl', category: 'Gastrointestinal', dosage: '20 mg 4 times daily', price: 14.00, indications: ['IBS', 'Abdominal cramps', 'GI spasms'], sideEffects: ['Dry mouth', 'Dizziness', 'Drowsiness'], image: '🧪', rating: 4.1 },
  { id: 145, name: 'Hyoscyamine', brand: 'Levsin', category: 'Gastrointestinal', dosage: '0.125-0.25 mg every 4 hours', price: 16.00, indications: ['IBS', 'Abdominal cramps', 'GI spasms'], sideEffects: ['Dry mouth', 'Dizziness', 'Drowsiness'], image: '🧪', rating: 4.0 },
  { id: 146, name: 'Ondansetron', brand: 'Zofran', category: 'Gastrointestinal', dosage: '4-8 mg 3 times daily', price: 25.00, indications: ['Nausea', 'Vomiting', 'Chemotherapy-induced nausea'], sideEffects: ['Headache', 'Constipation', 'Dizziness'], image: '🧪', rating: 4.5 },
  { id: 147, name: 'Metoclopramide', brand: 'Reglan', category: 'Gastrointestinal', dosage: '10-15 mg 3 times daily', price: 18.00, indications: ['GERD', 'Gastroparesis', 'Nausea'], sideEffects: ['Drowsiness', 'Restlessness', 'Diarrhea'], image: '🧪', rating: 3.9 },
  { id: 148, name: 'Promethazine', brand: 'Phenergan', category: 'Gastrointestinal', dosage: '12.5-25 mg 3 times daily', price: 15.00, indications: ['Nausea', 'Vomiting', 'Motion sickness'], sideEffects: ['Drowsiness', 'Dizziness', 'Dry mouth'], image: '🧪', rating: 4.0 },
  { id: 149, name: 'Prochlorperazine', brand: 'Compazine', category: 'Gastrointestinal', dosage: '5-10 mg 3 times daily', price: 16.00, indications: ['Nausea', 'Vomiting', 'Psychosis'], sideEffects: ['Drowsiness', 'Dizziness', 'Dry mouth'], image: '🧪', rating: 3.8 },
  { id: 150, name: 'Dronabinol', brand: 'Marinol', category: 'Gastrointestinal', dosage: '2.5-10 mg 2-3 times daily', price: 45.00, indications: ['Nausea', 'Vomiting', 'Appetite loss'], sideEffects: ['Dizziness', 'Drowsiness', 'Euphoria'], image: '🧪', rating: 4.0 },

  // ============================================
  // PSYCHIATRY (25 drugs)
  // ============================================
  { id: 151, name: 'Sertraline', brand: 'Zoloft', category: 'Psychiatry', dosage: '50 mg once daily', price: 25.00, indications: ['Depression', 'Anxiety', 'PTSD', 'OCD', 'PMDD'], sideEffects: ['Nausea', 'Insomnia', 'Drowsiness', 'Sexual dysfunction'], image: '🧠', rating: 4.5 },
  { id: 152, name: 'Fluoxetine', brand: 'Prozac', category: 'Psychiatry', dosage: '20 mg once daily', price: 20.00, indications: ['Depression', 'Anxiety', 'OCD', 'Bulimia', 'PMDD'], sideEffects: ['Nausea', 'Insomnia', 'Drowsiness', 'Sexual dysfunction'], image: '🧠', rating: 4.4 },
  { id: 153, name: 'Paroxetine', brand: 'Paxil', category: 'Psychiatry', dosage: '20-50 mg once daily', price: 22.00, indications: ['Depression', 'Anxiety', 'PTSD', 'OCD', 'PMDD'], sideEffects: ['Nausea', 'Insomnia', 'Drowsiness', 'Sexual dysfunction'], image: '🧠', rating: 4.2 },
  { id: 154, name: 'Citalopram', brand: 'Celexa', category: 'Psychiatry', dosage: '20-40 mg once daily', price: 18.00, indications: ['Depression', 'Anxiety'], sideEffects: ['Nausea', 'Insomnia', 'Drowsiness', 'Sexual dysfunction'], image: '🧠', rating: 4.3 },
  { id: 155, name: 'Escitalopram', brand: 'Lexapro', category: 'Psychiatry', dosage: '10-20 mg once daily', price: 20.00, indications: ['Depression', 'Anxiety', 'GAD'], sideEffects: ['Nausea', 'Insomnia', 'Drowsiness', 'Sexual dysfunction'], image: '🧠', rating: 4.5 },
  { id: 156, name: 'Duloxetine', brand: 'Cymbalta', category: 'Psychiatry', dosage: '30-60 mg once daily', price: 28.00, indications: ['Depression', 'Anxiety', 'Neuropathic pain', 'Fibromyalgia'], sideEffects: ['Nausea', 'Drowsiness', 'Insomnia', 'Sexual dysfunction'], image: '🧠', rating: 4.3 },
  { id: 157, name: 'Venlafaxine', brand: 'Effexor', category: 'Psychiatry', dosage: '37.5-225 mg daily', price: 26.00, indications: ['Depression', 'Anxiety', 'GAD', 'Panic disorder'], sideEffects: ['Nausea', 'Insomnia', 'Drowsiness', 'Sexual dysfunction'], image: '🧠', rating: 4.2 },
  { id: 158, name: 'Bupropion', brand: 'Wellbutrin', category: 'Psychiatry', dosage: '100-300 mg daily', price: 24.00, indications: ['Depression', 'Smoking cessation', 'SAD'], sideEffects: ['Insomnia', 'Headache', 'Nausea', 'Dry mouth'], image: '🧠', rating: 4.4 },
  { id: 159, name: 'Mirtazapine', brand: 'Remeron', category: 'Psychiatry', dosage: '15-45 mg once daily', price: 25.00, indications: ['Depression', 'Anxiety', 'Insomnia'], sideEffects: ['Drowsiness', 'Weight gain', 'Increased appetite'], image: '🧠', rating: 4.3 },
  { id: 160, name: 'Trazodone', brand: 'Desyrel', category: 'Psychiatry', dosage: '50-100 mg at bedtime', price: 15.00, indications: ['Depression', 'Insomnia', 'Anxiety'], sideEffects: ['Drowsiness', 'Dizziness', 'Dry mouth'], image: '🧠', rating: 4.0 },
  { id: 161, name: 'Buspirone', brand: 'BuSpar', category: 'Psychiatry', dosage: '10-30 mg 3 times daily', price: 22.00, indications: ['Anxiety disorder', 'GAD'], sideEffects: ['Dizziness', 'Nausea', 'Headache'], image: '🧠', rating: 4.1 },
  { id: 162, name: 'Amitriptyline', brand: 'Elavil', category: 'Psychiatry', dosage: '25-150 mg daily', price: 14.00, indications: ['Depression', 'Neuropathic pain', 'Migraine prevention'], sideEffects: ['Drowsiness', 'Dry mouth', 'Weight gain', 'Constipation'], image: '🧠', rating: 4.0 },
  { id: 163, name: 'Nortriptyline', brand: 'Pamelor', category: 'Psychiatry', dosage: '25-150 mg daily', price: 16.00, indications: ['Depression', 'Neuropathic pain', 'Smoking cessation'], sideEffects: ['Drowsiness', 'Dry mouth', 'Weight gain', 'Constipation'], image: '🧠', rating: 4.1 },
  { id: 164, name: 'Doxepin', brand: 'Sinequan', category: 'Psychiatry', dosage: '25-300 mg daily', price: 17.00, indications: ['Depression', 'Anxiety', 'Insomnia', 'Itching'], sideEffects: ['Drowsiness', 'Dry mouth', 'Weight gain', 'Constipation'], image: '🧠', rating: 3.9 },
  { id: 165, name: 'Clomipramine', brand: 'Anafranil', category: 'Psychiatry', dosage: '25-250 mg daily', price: 25.00, indications: ['OCD', 'Depression', 'Panic disorder'], sideEffects: ['Drowsiness', 'Dry mouth', 'Weight gain', 'Constipation'], image: '🧠', rating: 4.2 },
  { id: 166, name: 'Imipramine', brand: 'Tofranil', category: 'Psychiatry', dosage: '25-300 mg daily', price: 18.00, indications: ['Depression', 'Enuresis', 'Panic disorder'], sideEffects: ['Drowsiness', 'Dry mouth', 'Weight gain', 'Constipation'], image: '🧠', rating: 3.8 },
  { id: 167, name: 'Desipramine', brand: 'Norpramin', category: 'Psychiatry', dosage: '25-300 mg daily', price: 19.00, indications: ['Depression', 'Neuropathic pain'], sideEffects: ['Drowsiness', 'Dry mouth', 'Weight gain', 'Constipation'], image: '🧠', rating: 4.0 },
  { id: 168, name: 'Maprotiline', brand: 'Ludiomil', category: 'Psychiatry', dosage: '25-225 mg daily', price: 20.00, indications: ['Depression', 'Anxiety'], sideEffects: ['Drowsiness', 'Dry mouth', 'Weight gain', 'Constipation'], image: '🧠', rating: 3.8 },
  { id: 169, name: 'Phenelzine', brand: 'Nardil', category: 'Psychiatry', dosage: '15-90 mg daily', price: 35.00, indications: ['Depression', 'Anxiety', 'Social anxiety disorder'], sideEffects: ['Dizziness', 'Insomnia', 'Weight gain', 'Hypertensive crisis'], image: '🧠', rating: 4.0 },
  { id: 170, name: 'Tranylcypromine', brand: 'Parnate', category: 'Psychiatry', dosage: '10-60 mg daily', price: 38.00, indications: ['Depression', 'Anxiety'], sideEffects: ['Dizziness', 'Insomnia', 'Weight gain', 'Hypertensive crisis'], image: '🧠', rating: 4.1 },
  { id: 171, name: 'Alprazolam', brand: 'Xanax', category: 'Psychiatry', dosage: '0.25-1 mg 3 times daily', price: 18.00, indications: ['Anxiety', 'Panic disorder', 'Insomnia'], sideEffects: ['Drowsiness', 'Dizziness', 'Addiction'], image: '🧠', rating: 4.2 },
  { id: 172, name: 'Lorazepam', brand: 'Ativan', category: 'Psychiatry', dosage: '0.5-2 mg 3 times daily', price: 16.00, indications: ['Anxiety', 'Insomnia', 'Seizures'], sideEffects: ['Drowsiness', 'Dizziness', 'Addiction'], image: '🧠', rating: 4.3 },
  { id: 173, name: 'Diazepam', brand: 'Valium', category: 'Psychiatry', dosage: '2-10 mg 3 times daily', price: 14.00, indications: ['Anxiety', 'Muscle spasms', 'Seizures', 'Insomnia'], sideEffects: ['Drowsiness', 'Dizziness', 'Addiction'], image: '🧠', rating: 4.1 },
  { id: 174, name: 'Clonazepam', brand: 'Klonopin', category: 'Psychiatry', dosage: '0.5-2 mg 3 times daily', price: 20.00, indications: ['Anxiety', 'Panic disorder', 'Seizures', 'Restless leg syndrome'], sideEffects: ['Drowsiness', 'Dizziness', 'Addiction'], image: '🧠', rating: 4.2 },
  { id: 175, name: 'Zolpidem', brand: 'Ambien', category: 'Psychiatry', dosage: '5-10 mg at bedtime', price: 22.00, indications: ['Insomnia'], sideEffects: ['Drowsiness', 'Dizziness', 'Sleepwalking'], image: '🧠', rating: 4.0 },

  // ============================================
  // ANTIHISTAMINES (15 drugs)
  // ============================================
  { id: 176, name: 'Cetirizine', brand: 'Zyrtec', category: 'Antihistamine', dosage: '10 mg once daily', price: 9.00, indications: ['Allergies', 'Hay fever', 'Hives', 'Itching'], sideEffects: ['Drowsiness', 'Headache', 'Dry mouth'], image: '🤧', rating: 4.5 },
  { id: 177, name: 'Loratadine', brand: 'Claritin', category: 'Antihistamine', dosage: '10 mg once daily', price: 8.00, indications: ['Allergies', 'Hay fever', 'Hives', 'Itching'], sideEffects: ['Drowsiness', 'Headache', 'Dry mouth'], image: '🤧', rating: 4.4 },
  { id: 178, name: 'Fexofenadine', brand: 'Allegra', category: 'Antihistamine', dosage: '180 mg once daily', price: 12.00, indications: ['Allergies', 'Hay fever', 'Hives', 'Itching'], sideEffects: ['Headache', 'Dry mouth', 'Dizziness'], image: '🤧', rating: 4.3 },
  { id: 179, name: 'Desloratadine', brand: 'Aerius', category: 'Antihistamine', dosage: '5 mg once daily', price: 14.00, indications: ['Allergies', 'Hay fever', 'Hives', 'Itching'], sideEffects: ['Headache', 'Dry mouth', 'Dizziness'], image: '��', rating: 4.4 },
  { id: 180, name: 'Levocetirizine', brand: 'Xyzal', category: 'Antihistamine', dosage: '5 mg once daily', price: 13.00, indications: ['Allergies', 'Hay fever', 'Hives', 'Itching'], sideEffects: ['Drowsiness', 'Headache', 'Dry mouth'], image: '🤧', rating: 4.3 },
  { id: 181, name: 'Bilastine', brand: 'Bilaxten', category: 'Antihistamine', dosage: '20 mg once daily', price: 15.00, indications: ['Allergies', 'Hay fever', 'Hives'], sideEffects: ['Headache', 'Dry mouth', 'Dizziness'], image: '🤧', rating: 4.2 },
  { id: 182, name: 'Rupatadine', brand: 'Rupafin', category: 'Antihistamine', dosage: '10 mg once daily', price: 16.00, indications: ['Allergies', 'Hay fever', 'Hives'], sideEffects: ['Headache', 'Dry mouth', 'Dizziness'], image: '🤧', rating: 4.1 },
  { id: 183, name: 'Ebastine', brand: 'Ebastel', category: 'Antihistamine', dosage: '10-20 mg once daily', price: 12.00, indications: ['Allergies', 'Hay fever', 'Hives'], sideEffects: ['Headache', 'Dry mouth', 'Dizziness'], image: '🤧', rating: 4.0 },
  { id: 184, name: 'Mizolastine', brand: 'Mizollen', category: 'Antihistamine', dosage: '10 mg once daily', price: 14.00, indications: ['Allergies', 'Hay fever', 'Hives'], sideEffects: ['Headache', 'Dry mouth', 'Dizziness'], image: '🤧', rating: 4.0 },
  { id: 185, name: 'Acrivastine', brand: 'Semprex-D', category: 'Antihistamine', dosage: '8 mg 3 times daily', price: 11.00, indications: ['Allergies', 'Hay fever'], sideEffects: ['Headache', 'Dry mouth', 'Dizziness'], image: '🤧', rating: 4.1 },
  { id: 186, name: 'Diphenhydramine', brand: 'Benadryl', category: 'Antihistamine', dosage: '25-50 mg every 4-6 hours', price: 7.00, indications: ['Allergies', 'Insomnia', 'Motion sickness', 'Cough'], sideEffects: ['Drowsiness', 'Dizziness', 'Dry mouth'], image: '🤧', rating: 4.0 },
  { id: 187, name: 'Chlorpheniramine', brand: 'Chlor-Trimeton', category: 'Antihistamine', dosage: '4 mg every 4-6 hours', price: 6.00, indications: ['Allergies', 'Hay fever', 'Hives'], sideEffects: ['Drowsiness', 'Dizziness', 'Dry mouth'], image: '🤧', rating: 3.8 },
  { id: 188, name: 'Doxylamine', brand: 'Unisom', category: 'Antihistamine', dosage: '25 mg at bedtime', price: 8.00, indications: ['Insomnia', 'Allergies', 'Motion sickness'], sideEffects: ['Drowsiness', 'Dizziness', 'Dry mouth'], image: '🤧', rating: 3.9 },
  { id: 189, name: 'Hydroxyzine', brand: 'Vistaril', category: 'Antihistamine', dosage: '25-100 mg 3 times daily', price: 12.00, indications: ['Anxiety', 'Allergies', 'Insomnia', 'Itching'], sideEffects: ['Drowsiness', 'Dizziness', 'Dry mouth'], image: '🤧', rating: 4.0 },
  { id: 190, name: 'Promethazine', brand: 'Phenergan', category: 'Antihistamine', dosage: '12.5-25 mg 3 times daily', price: 15.00, indications: ['Nausea', 'Allergies', 'Insomnia', 'Motion sickness'], sideEffects: ['Drowsiness', 'Dizziness', 'Dry mouth'], image: '🤧', rating: 4.0 },

  // ============================================
  // HORMONES (20 drugs)
  // ============================================
  { id: 191, name: 'Levothyroxine', brand: 'Synthroid', category: 'Hormones', dosage: '25-200 mcg once daily', price: 16.00, indications: ['Hypothyroidism', 'Thyroid cancer', 'Myxedema'], sideEffects: ['Weight changes', 'Insomnia', 'Palpitations'], image: '🧬', rating: 4.5 },
  { id: 192, name: 'Prednisolone', brand: 'Wysolone', category: 'Hormones', dosage: '5-60 mg daily', price: 13.00, indications: ['Inflammation', 'Allergies', 'Asthma', 'Autoimmune diseases'], sideEffects: ['Weight gain', 'Insomnia', 'Mood changes', 'Osteoporosis'], image: '🧬', rating: 4.3 },
  { id: 193, name: 'Hydrocortisone', brand: 'Cortef', category: 'Hormones', dosage: '10-40 mg 3 times daily', price: 20.00, indications: ['Adrenal insufficiency', 'Inflammation', 'Allergies'], sideEffects: ['Weight gain', 'Insomnia', 'Mood changes'], image: '🧬', rating: 4.2 },
  { id: 194, name: 'Dexamethasone', brand: 'Decadron', category: 'Hormones', dosage: '4-16 mg daily', price: 18.00, indications: ['Inflammation', 'Allergies', 'Cancer', 'Autoimmune diseases'], sideEffects: ['Weight gain', 'Insomnia', 'Mood changes'], image: '🧬', rating: 4.4 },
  { id: 195, name: 'Methylprednisolone', brand: 'Medrol', category: 'Hormones', dosage: '4-48 mg daily', price: 19.00, indications: ['Inflammation', 'Allergies', 'Asthma', 'Autoimmune diseases'], sideEffects: ['Weight gain', 'Insomnia', 'Mood changes'], image: '🧬', rating: 4.3 },
  { id: 196, name: 'Estradiol', brand: 'Estrace', category: 'Hormones', dosage: '1-2 mg once daily', price: 25.00, indications: ['Menopause symptoms', 'Hormone replacement', 'Osteoporosis'], sideEffects: ['Nausea', 'Breast tenderness', 'Headache'], image: '🧬', rating: 4.0 },
  { id: 197, name: 'Progesterone', brand: 'Prometrium', category: 'Hormones', dosage: '100-200 mg daily', price: 22.00, indications: ['Menopause symptoms', 'HRT', 'Irregular periods'], sideEffects: ['Drowsiness', 'Nausea', 'Headache'], image: '🧬', rating: 4.1 },
  { id: 198, name: 'Testosterone', brand: 'Androgel', category: 'Hormones', dosage: '50-100 mg daily', price: 45.00, indications: ['Low testosterone', 'Hypogonadism'], sideEffects: ['Acne', 'Mood changes', 'Sleep apnea'], image: '🧬', rating: 4.2 },
  { id: 199, name: 'Prednisone', brand: 'Deltasone', category: 'Hormones', dosage: '5-60 mg daily', price: 12.00, indications: ['Inflammation', 'Allergies', 'Autoimmune diseases', 'Asthma'], sideEffects: ['Weight gain', 'Insomnia', 'Mood changes'], image: '🧬', rating: 4.1 },
  { id: 200, name: 'Fludrocortisone', brand: 'Florinef', category: 'Hormones', dosage: '0.1-0.2 mg daily', price: 28.00, indications: ['Adrenal insufficiency', 'Salt-losing disorders'], sideEffects: ['Hypertension', 'Edema', 'Headache'], image: '🧬', rating: 4.0 },
  { id: 201, name: 'Liothyronine', brand: 'Cytomel', category: 'Hormones', dosage: '25-50 mcg daily', price: 22.00, indications: ['Hypothyroidism', 'Myxedema', 'Thyroid cancer'], sideEffects: ['Palpitations', 'Insomnia', 'Weight loss'], image: '🧬', rating: 4.2 },
  { id: 202, name: 'Norethindrone', brand: 'Aygestin', category: 'Hormones', dosage: '5-15 mg daily', price: 20.00, indications: ['Endometriosis', 'Abnormal bleeding', 'Contraception'], sideEffects: ['Nausea', 'Headache', 'Weight gain'], image: '🧬', rating: 4.0 },
  { id: 203, name: 'Medroxyprogesterone', brand: 'Provera', category: 'Hormones', dosage: '2.5-10 mg daily', price: 18.00, indications: ['Menopause symptoms', 'Abnormal bleeding', 'Contraception'], sideEffects: ['Nausea', 'Headache', 'Weight gain'], image: '🧬', rating: 4.0 },
  { id: 204, name: 'Danazol', brand: 'Danocrine', category: 'Hormones', dosage: '200-800 mg daily', price: 35.00, indications: ['Endometriosis', 'Fibrocystic breast disease'], sideEffects: ['Weight gain', 'Acne', 'Mood changes'], image: '🧬', rating: 3.8 },
  { id: 205, name: 'Bromocriptine', brand: 'Parlodel', category: 'Hormones', dosage: '2.5-5 mg daily', price: 30.00, indications: ['Parkinson\'s disease', 'Hyperprolactinemia', 'Acromegaly'], sideEffects: ['Nausea', 'Dizziness', 'Headache'], image: '🧬', rating: 4.0 },
  { id: 206, name: 'Cabergoline', brand: 'Dostinex', category: 'Hormones', dosage: '0.5-1 mg twice weekly', price: 35.00, indications: ['Hyperprolactinemia', 'Parkinson\'s disease'], sideEffects: ['Nausea', 'Dizziness', 'Headache'], image: '🧬', rating: 4.1 },
  { id: 207, name: 'Leuprolide', brand: 'Lupron', category: 'Hormones', dosage: '3.75-11.25 mg monthly', price: 50.00, indications: ['Endometriosis', 'Prostate cancer', 'Fibroids'], sideEffects: ['Hot flashes', 'Nausea', 'Headache'], image: '🧬', rating: 4.2 },
  { id: 208, name: 'Goserelin', brand: 'Zoladex', category: 'Hormones', dosage: '3.6-10.8 mg monthly', price: 55.00, indications: ['Prostate cancer', 'Breast cancer', 'Endometriosis'], sideEffects: ['Hot flashes', 'Nausea', 'Headache'], image: '🧬', rating: 4.1 },
  { id: 209, name: 'Triptorelin', brand: 'Trelstar', category: 'Hormones', dosage: '3.75-11.25 mg monthly', price: 52.00, indications: ['Prostate cancer', 'Endometriosis', 'Fibroids'], sideEffects: ['Hot flashes', 'Nausea', 'Headache'], image: '��', rating: 4.0 },
  { id: 210, name: 'Histrelin', brand: 'Supprelin LA', category: 'Hormones', dosage: '50 mg implant', price: 60.00, indications: ['Central precocious puberty', 'Endometriosis'], sideEffects: ['Hot flashes', 'Nausea', 'Headache'], image: '🧬', rating: 4.1 },
];

// ===== EXPORT FUNCTIONS =====
export const getDrugById = (id) => {
  return drugDatabase.find(drug => drug.id === id);
};

export const getCategories = () => {
  return [...new Set(drugDatabase.map(d => d.category).filter(Boolean))];
};

export const searchDrugs = (query) => {
  if (!query) return drugDatabase;
  const term = query.toLowerCase();
  return drugDatabase.filter(d => 
    d.name?.toLowerCase().includes(term) ||
    d.category?.toLowerCase().includes(term) ||
    (d.indications && d.indications.some(i => i.toLowerCase().includes(term))) ||
    d.brand?.toLowerCase().includes(term)
  );
};

export default drugDatabase;
