// Fallback data in case the SDK doesn't work
export const fallbackDrugs = [
  {
    id: 1,
    name: 'Amoxicillin',
    category: 'Anti-infective',
    dosage: '250-500 mg every 8 hours',
    maxDose: '4000 mg/day',
    forms: ['Capsule', 'Tablet', 'Suspension', 'Injection'],
    indications: ['Respiratory infections', 'UTI', 'Skin infections'],
    contraindications: ['Penicillin allergy'],
    sideEffects: ['Nausea', 'Diarrhea', 'Rash'],
    interactions: ['Allopurinol', 'Warfarin'],
    countries: ['WHO', 'USA', 'UK', 'India', 'Australia', 'Canada', 'EU'],
  },
  {
    id: 2,
    name: 'Lisinopril',
    category: 'Cardiovascular',
    dosage: '10-20 mg once daily',
    maxDose: '40 mg/day',
    forms: ['Tablet'],
    indications: ['High blood pressure', 'Heart failure'],
    contraindications: ['Pregnancy'],
    sideEffects: ['Cough', 'Dizziness', 'Headache'],
    interactions: ['Potassium supplements', 'NSAIDs'],
    countries: ['WHO', 'USA', 'UK', 'India', 'Australia', 'Canada', 'EU'],
  },
  {
    id: 3,
    name: 'Metformin',
    category: 'Diabetes',
    dosage: '500-1000 mg twice daily',
    maxDose: '2550 mg/day',
    forms: ['Tablet', 'Extended Release'],
    indications: ['Type 2 diabetes', 'PCOS'],
    contraindications: ['Renal impairment'],
    sideEffects: ['Nausea', 'Diarrhea', 'Stomach upset'],
    interactions: ['Furosemide', 'Digoxin'],
    countries: ['WHO', 'USA', 'UK', 'India', 'Australia', 'Canada', 'EU'],
  },
];
