USE wellnessos_db;

INSERT INTO appointments (user_id, doctor_id, appointment_date, appointment_time, type, status, notes) VALUES
(1, 1, DATE_ADD(CURDATE(), INTERVAL 1 DAY), '09:00 AM', 'In-Person', 'Confirmed', 'Routine checkup'),
(1, 2, DATE_ADD(CURDATE(), INTERVAL 2 DAY), '10:30 AM', 'Video', 'Scheduled', 'Follow-up visit'),
(1, 3, DATE_ADD(CURDATE(), INTERVAL 3 DAY), '02:00 PM', 'In-Person', 'Confirmed', 'Annual physical'),
(1, 4, DATE_ADD(CURDATE(), INTERVAL 4 DAY), '11:15 AM', 'Phone', 'Scheduled', 'Consultation'),
(1, 5, DATE_ADD(CURDATE(), INTERVAL 5 DAY), '03:45 PM', 'Video', 'Confirmed', 'Test results review'),
(1, 6, DATE_ADD(CURDATE(), INTERVAL 6 DAY), '08:30 AM', 'In-Person', 'Scheduled', 'New patient visit'),
(1, 7, DATE_ADD(CURDATE(), INTERVAL 7 DAY), '01:00 PM', 'Video', 'Confirmed', 'Pre-surgery consultation'),
(1, 8, DATE_ADD(CURDATE(), INTERVAL 8 DAY), '04:15 PM', 'In-Person', 'Scheduled', 'Post-surgery follow-up'),
(1, 9, DATE_ADD(CURDATE(), INTERVAL 9 DAY), '09:45 AM', 'Phone', 'Confirmed', 'Vaccination'),
(1, 10, DATE_ADD(CURDATE(), INTERVAL 10 DAY), '11:30 AM', 'Video', 'Scheduled', 'Emergency visit'),
(2, 1, DATE_ADD(CURDATE(), INTERVAL 1 DAY), '10:00 AM', 'Video', 'Confirmed', 'Routine checkup'),
(2, 2, DATE_ADD(CURDATE(), INTERVAL 3 DAY), '02:30 PM', 'In-Person', 'Scheduled', 'Follow-up visit'),
(2, 3, DATE_ADD(CURDATE(), INTERVAL 5 DAY), '09:15 AM', 'Video', 'Confirmed', 'Annual physical'),
(2, 4, DATE_ADD(CURDATE(), INTERVAL 7 DAY), '01:45 PM', 'Phone', 'Scheduled', 'Consultation'),
(2, 5, DATE_ADD(CURDATE(), INTERVAL 9 DAY), '03:00 PM', 'In-Person', 'Confirmed', 'Test results review'),
(2, 6, DATE_ADD(CURDATE(), INTERVAL 11 DAY), '08:00 AM', 'Video', 'Scheduled', 'New patient visit'),
(2, 7, DATE_ADD(CURDATE(), INTERVAL 13 DAY), '12:30 PM', 'In-Person', 'Confirmed', 'Pre-surgery consultation'),
(2, 8, DATE_ADD(CURDATE(), INTERVAL 15 DAY), '04:45 PM', 'Video', 'Scheduled', 'Post-surgery follow-up'),
(2, 9, DATE_ADD(CURDATE(), INTERVAL 17 DAY), '10:15 AM', 'Phone', 'Confirmed', 'Vaccination'),
(2, 10, DATE_ADD(CURDATE(), INTERVAL 19 DAY), '02:00 PM', 'In-Person', 'Scheduled', 'Emergency visit'),
(3, 1, DATE_ADD(CURDATE(), INTERVAL 2 DAY), '11:00 AM', 'In-Person', 'Confirmed', 'Routine checkup'),
(3, 2, DATE_ADD(CURDATE(), INTERVAL 4 DAY), '03:30 PM', 'Video', 'Scheduled', 'Follow-up visit'),
(3, 3, DATE_ADD(CURDATE(), INTERVAL 6 DAY), '09:30 AM', 'In-Person', 'Confirmed', 'Annual physical'),
(3, 4, DATE_ADD(CURDATE(), INTERVAL 8 DAY), '02:15 PM', 'Phone', 'Scheduled', 'Consultation'),
(3, 5, DATE_ADD(CURDATE(), INTERVAL 10 DAY), '04:00 PM', 'Video', 'Confirmed', 'Test results review'),
(3, 6, DATE_ADD(CURDATE(), INTERVAL 12 DAY), '08:45 AM', 'In-Person', 'Scheduled', 'New patient visit'),
(3, 7, DATE_ADD(CURDATE(), INTERVAL 14 DAY), '01:15 PM', 'Video', 'Confirmed', 'Pre-surgery consultation'),
(3, 8, DATE_ADD(CURDATE(), INTERVAL 16 DAY), '05:00 PM', 'In-Person', 'Scheduled', 'Post-surgery follow-up'),
(3, 9, DATE_ADD(CURDATE(), INTERVAL 18 DAY), '10:45 AM', 'Phone', 'Confirmed', 'Vaccination'),
(3, 10, DATE_ADD(CURDATE(), INTERVAL 20 DAY), '02:30 PM', 'Video', 'Scheduled', 'Emergency visit'),
(4, 1, DATE_ADD(CURDATE(), INTERVAL 3 DAY), '09:15 AM', 'Video', 'Confirmed', 'Routine checkup'),
(4, 2, DATE_ADD(CURDATE(), INTERVAL 5 DAY), '11:45 AM', 'In-Person', 'Scheduled', 'Follow-up visit'),
(4, 3, DATE_ADD(CURDATE(), INTERVAL 7 DAY), '03:15 PM', 'Video', 'Confirmed', 'Annual physical'),
(4, 4, DATE_ADD(CURDATE(), INTERVAL 9 DAY), '08:30 AM', 'Phone', 'Scheduled', 'Consultation'),
(4, 5, DATE_ADD(CURDATE(), INTERVAL 11 DAY), '12:45 PM', 'In-Person', 'Confirmed', 'Test results review'),
(4, 6, DATE_ADD(CURDATE(), INTERVAL 13 DAY), '04:15 PM', 'Video', 'Scheduled', 'New patient visit'),
(4, 7, DATE_ADD(CURDATE(), INTERVAL 15 DAY), '09:45 AM', 'In-Person', 'Confirmed', 'Pre-surgery consultation'),
(4, 8, DATE_ADD(CURDATE(), INTERVAL 17 DAY), '01:30 PM', 'Video', 'Scheduled', 'Post-surgery follow-up'),
(4, 9, DATE_ADD(CURDATE(), INTERVAL 19 DAY), '03:45 PM', 'Phone', 'Confirmed', 'Vaccination'),
(4, 10, DATE_ADD(CURDATE(), INTERVAL 21 DAY), '10:30 AM', 'In-Person', 'Scheduled', 'Emergency visit'),
(5, 1, DATE_ADD(CURDATE(), INTERVAL 4 DAY), '10:15 AM', 'In-Person', 'Confirmed', 'Routine checkup'),
(5, 2, DATE_ADD(CURDATE(), INTERVAL 6 DAY), '12:45 PM', 'Video', 'Scheduled', 'Follow-up visit'),
(5, 3, DATE_ADD(CURDATE(), INTERVAL 8 DAY), '02:30 PM', 'In-Person', 'Confirmed', 'Annual physical'),
(5, 4, DATE_ADD(CURDATE(), INTERVAL 10 DAY), '04:30 PM', 'Phone', 'Scheduled', 'Consultation'),
(5, 5, DATE_ADD(CURDATE(), INTERVAL 12 DAY), '09:00 AM', 'Video', 'Confirmed', 'Test results review'),
(5, 6, DATE_ADD(CURDATE(), INTERVAL 14 DAY), '11:15 AM', 'In-Person', 'Scheduled', 'New patient visit'),
(5, 7, DATE_ADD(CURDATE(), INTERVAL 16 DAY), '03:45 PM', 'Video', 'Confirmed', 'Pre-surgery consultation'),
(5, 8, DATE_ADD(CURDATE(), INTERVAL 18 DAY), '05:15 PM', 'In-Person', 'Scheduled', 'Post-surgery follow-up'),
(5, 9, DATE_ADD(CURDATE(), INTERVAL 20 DAY), '08:15 AM', 'Phone', 'Confirmed', 'Vaccination'),
(5, 10, DATE_ADD(CURDATE(), INTERVAL 22 DAY), '12:00 PM', 'Video', 'Scheduled', 'Emergency visit'),
(1, 1, DATE_ADD(CURDATE(), INTERVAL 11 DAY), '09:30 AM', 'Video', 'Confirmed', 'Routine checkup'),
(1, 2, DATE_ADD(CURDATE(), INTERVAL 12 DAY), '11:00 AM', 'In-Person', 'Scheduled', 'Follow-up visit'),
(1, 3, DATE_ADD(CURDATE(), INTERVAL 13 DAY), '02:45 PM', 'Video', 'Confirmed', 'Annual physical'),
(1, 4, DATE_ADD(CURDATE(), INTERVAL 14 DAY), '10:30 AM', 'Phone', 'Scheduled', 'Consultation'),
(1, 5, DATE_ADD(CURDATE(), INTERVAL 15 DAY), '01:15 PM', 'In-Person', 'Confirmed', 'Test results review'),
(1, 6, DATE_ADD(CURDATE(), INTERVAL 16 DAY), '04:30 PM', 'Video', 'Scheduled', 'New patient visit'),
(1, 7, DATE_ADD(CURDATE(), INTERVAL 17 DAY), '09:00 AM', 'In-Person', 'Confirmed', 'Pre-surgery consultation'),
(1, 8, DATE_ADD(CURDATE(), INTERVAL 18 DAY), '11:45 AM', 'Video', 'Scheduled', 'Post-surgery follow-up'),
(1, 9, DATE_ADD(CURDATE(), INTERVAL 19 DAY), '03:30 PM', 'Phone', 'Confirmed', 'Vaccination'),
(1, 10, DATE_ADD(CURDATE(), INTERVAL 20 DAY), '08:45 AM', 'In-Person', 'Scheduled', 'Emergency visit'),
(2, 1, DATE_ADD(CURDATE(), INTERVAL 21 DAY), '10:00 AM', 'Video', 'Confirmed', 'Routine checkup'),
(2, 2, DATE_ADD(CURDATE(), INTERVAL 22 DAY), '12:30 PM', 'In-Person', 'Scheduled', 'Follow-up visit'),
(2, 3, DATE_ADD(CURDATE(), INTERVAL 23 DAY), '02:15 PM', 'Video', 'Confirmed', 'Annual physical'),
(2, 4, DATE_ADD(CURDATE(), INTERVAL 24 DAY), '09:45 AM', 'Phone', 'Scheduled', 'Consultation'),
(2, 5, DATE_ADD(CURDATE(), INTERVAL 25 DAY), '11:30 AM', 'In-Person', 'Confirmed', 'Test results review'),
(2, 6, DATE_ADD(CURDATE(), INTERVAL 26 DAY), '04:00 PM', 'Video', 'Scheduled', 'New patient visit'),
(2, 7, DATE_ADD(CURDATE(), INTERVAL 27 DAY), '08:30 AM', 'In-Person', 'Confirmed', 'Pre-surgery consultation'),
(2, 8, DATE_ADD(CURDATE(), INTERVAL 28 DAY), '01:00 PM', 'Video', 'Scheduled', 'Post-surgery follow-up'),
(2, 9, DATE_ADD(CURDATE(), INTERVAL 29 DAY), '03:15 PM', 'Phone', 'Confirmed', 'Vaccination'),
(2, 10, DATE_ADD(CURDATE(), INTERVAL 30 DAY), '10:45 AM', 'In-Person', 'Scheduled', 'Emergency visit'),
(3, 1, DATE_ADD(CURDATE(), INTERVAL 31 DAY), '09:15 AM', 'In-Person', 'Confirmed', 'Routine checkup'),
(3, 2, DATE_ADD(CURDATE(), INTERVAL 32 DAY), '11:45 AM', 'Video', 'Scheduled', 'Follow-up visit'),
(3, 3, DATE_ADD(CURDATE(), INTERVAL 33 DAY), '03:00 PM', 'In-Person', 'Confirmed', 'Annual physical'),
(3, 4, DATE_ADD(CURDATE(), INTERVAL 34 DAY), '08:00 AM', 'Phone', 'Scheduled', 'Consultation'),
(3, 5, DATE_ADD(CURDATE(), INTERVAL 35 DAY), '12:15 PM', 'Video', 'Confirmed', 'Test results review'),
(3, 6, DATE_ADD(CURDATE(), INTERVAL 36 DAY), '04:45 PM', 'In-Person', 'Scheduled', 'New patient visit'),
(3, 7, DATE_ADD(CURDATE(), INTERVAL 37 DAY), '09:30 AM', 'Video', 'Confirmed', 'Pre-surgery consultation'),
(3, 8, DATE_ADD(CURDATE(), INTERVAL 38 DAY), '01:45 PM', 'In-Person', 'Scheduled', 'Post-surgery follow-up'),
(3, 9, DATE_ADD(CURDATE(), INTERVAL 39 DAY), '03:45 PM', 'Phone', 'Confirmed', 'Vaccination'),
(3, 10, DATE_ADD(CURDATE(), INTERVAL 40 DAY), '10:00 AM', 'Video', 'Scheduled', 'Emergency visit'),
(4, 1, DATE_ADD(CURDATE(), INTERVAL 41 DAY), '10:30 AM', 'Video', 'Confirmed', 'Routine checkup'),
(4, 2, DATE_ADD(CURDATE(), INTERVAL 42 DAY), '02:00 PM', 'In-Person', 'Scheduled', 'Follow-up visit'),
(4, 3, DATE_ADD(CURDATE(), INTERVAL 43 DAY), '09:45 AM', 'Video', 'Confirmed', 'Annual physical'),
(4, 4, DATE_ADD(CURDATE(), INTERVAL 44 DAY), '11:15 AM', 'Phone', 'Scheduled', 'Consultation'),
(4, 5, DATE_ADD(CURDATE(), INTERVAL 45 DAY), '04:15 PM', 'In-Person', 'Confirmed', 'Test results review'),
(4, 6, DATE_ADD(CURDATE(), INTERVAL 46 DAY), '08:15 AM', 'Video', 'Scheduled', 'New patient visit'),
(4, 7, DATE_ADD(CURDATE(), INTERVAL 47 DAY), '12:45 PM', 'In-Person', 'Confirmed', 'Pre-surgery consultation'),
(4, 8, DATE_ADD(CURDATE(), INTERVAL 48 DAY), '03:30 PM', 'Video', 'Scheduled', 'Post-surgery follow-up'),
(4, 9, DATE_ADD(CURDATE(), INTERVAL 49 DAY), '05:00 PM', 'Phone', 'Confirmed', 'Vaccination'),
(4, 10, DATE_ADD(CURDATE(), INTERVAL 50 DAY), '09:00 AM', 'In-Person', 'Scheduled', 'Emergency visit'),
(5, 1, DATE_ADD(CURDATE(), INTERVAL 51 DAY), '11:00 AM', 'In-Person', 'Confirmed', 'Routine checkup'),
(5, 2, DATE_ADD(CURDATE(), INTERVAL 52 DAY), '01:30 PM', 'Video', 'Scheduled', 'Follow-up visit'),
(5, 3, DATE_ADD(CURDATE(), INTERVAL 53 DAY), '03:45 PM', 'In-Person', 'Confirmed', 'Annual physical'),
(5, 4, DATE_ADD(CURDATE(), INTERVAL 54 DAY), '10:15 AM', 'Phone', 'Scheduled', 'Consultation'),
(5, 5, DATE_ADD(CURDATE(), INTERVAL 55 DAY), '12:00 PM', 'Video', 'Confirmed', 'Test results review'),
(5, 6, DATE_ADD(CURDATE(), INTERVAL 56 DAY), '02:45 PM', 'In-Person', 'Scheduled', 'New patient visit'),
(5, 7, DATE_ADD(CURDATE(), INTERVAL 57 DAY), '04:30 PM', 'Video', 'Confirmed', 'Pre-surgery consultation'),
(5, 8, DATE_ADD(CURDATE(), INTERVAL 58 DAY), '09:15 AM', 'In-Person', 'Scheduled', 'Post-surgery follow-up'),
(5, 9, DATE_ADD(CURDATE(), INTERVAL 59 DAY), '11:45 AM', 'Phone', 'Confirmed', 'Vaccination'),
(5, 10, DATE_ADD(CURDATE(), INTERVAL 60 DAY), '02:15 PM', 'Video', 'Scheduled', 'Emergency visit');
